package constants

// Role permissions offsets
const (
	VIEW_GUILD_CHANNEL_PERMISSION = iota
	MANAGE_GUILD_CHANNELS_PERMISSION
	CREATE_CHANNEL_MESSAGE_PERMISSION
	MANAGE_CHANNEL_MESSAGES_PERMISSION
	MANAGE_GUILD_PERMISSION
	GUILD_ADMIN_PERMISSION
	GUILD_SUPER_ADMIN_PERMISSION
	GUILD_OWNER_PERMISSION
	VIEW_GUILD_MEMBERS_PERMISSION
	CREATE_CHANNEL_PIN_PERMISSION
)

// User PublicFlags
const (
	ALLOW_GUILD_MEMBER_DM = iota
	ALLOW_FRIEND_REQUEST
)
