version: "3.8"
name: "Accord-Prod"
services:
  db:
    image: postgres:15
    networks:
      accord_prod_net:
        aliases:
          - db
    restart: always
    volumes:
      - prod_db_data:/var/lib/postgresql/data
      - PATH_TO_DB_SCHEMA
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust

  mq:
    image: rabbitmq
    networks:
      accord_prod_net:
        aliases:
          - mq
    restart: always
    volumes:
      - prod_mq_data:/var/lib/rabbitmq

  accord-rest-api:
    image: miket117/accord-rest-api
    ports:
      - "4000:4000"
    networks:
      accord_prod_net:
        aliases:
          - rest
    depends_on:
      - mq
      - db
    environment:
      ACCESS_TOKEN_SECRET:
      REFRESH_TOKEN_SECRET:
      FASTIFY_ADDRESS: 0.0.0.0
      FASTIFY_PORT: 4000
      AMQP_HOST: mq
      PUBLIC_URL:
      CORS_ORIGIN:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      OAUTH_STATE_SECRET:
      OAUTH_ERROR_REDIRECT_URL: https://HOST?error=true
      OAUTH_GITHUB_CLIENT_ID:
      OAUTH_GITHUB_REDIRECT_URI: https://HOST/api/v1/auth/github/callback
      OAUTH_GITHUB_CLIENT_SECRET:
      OAUTH_GITHUB_TOKEN_VALIDATION_URI: https://api.github.com/applications/GITHUB_APP_ID/token
      OAUTH_GITHUB_BASIC_AUTH:
      CLOUDINARY_API_SECRET:
      CLOUDINARY_UPLOAD_PRESET:
      CLOUDINARY_CLOUD_NAME:
      CLOUDINARY_API_KEY:
      CLOUDINARY_UPLOAD_PATH:

  accord-websocket-server:
    image: miket117/accord-websocket-server
    ports:
      - "4001:4001"
    networks:
      accord_prod_net:
        aliases:
          - websocket
    depends_on:
      - mq
      - db
    environment:
      PORT: 4001
      ACCESS_TOKEN_SECRET:
      REFRESH_TOKEN_SECRET:
      AMQP_HOST: mq
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432

  accord-voice-server:
    image: miket117/accord-voice-server
    ports:
      - "4002:4002"
      - "11000-11000:11000-11000/udp"
    networks:
      accord_prod_net:
        aliases:
          - voice
    depends_on:
      - mq
      - db
    environment:
      ACCESS_TOKEN_SECRET:
      REFRESH_TOKEN_SECRET:
      AMQP_HOST: mq
      PORT: 4002
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      OAUTH_GITHUB_TOKEN_VALIDATION_URI: https://api.github.com/applications/GITHUB_APP_ID/token
      OAUTH_GITHUB_BASIC_AUTH:

  accord-react-app:
    image: miket117/accord-react-app
    ports:
      - "3000:80"
    depends_on:
      - accord-rest-api
      - accord-websocket-server
      - accord-voice-server
    environment:
      CLOUDINARY_URL:
      CLOUDINARY_API_KEY:
      WS_URL: HOST/ws
      API_URL: HOST/api
      RTC_URL: HOST/rtc

volumes:
  prod_db_data:
  prod_mq_data:

networks:
  accord_prod_net:
    name: accord_prod_network
