export const AccordForwardingMessageQueue = {
  USER_RELATIONSHIP: "USER_RELATIONSHIP",
  USER: "USER",
  USER_ROLE: "USER_ROLE",
  GUILD_ROLE: "GUILD_ROLE",
  GUILD: "GUILD",
  GUILD_MEMBER: "GUILD_MEMBER",
  CHANNEL: "CHANNEL",
  CHANNEL_PIN: "CHANNEL_PIN",
  CHANNEL_MESSAGE: "CHANNEL_MESSAGE",
  VOICE_CHANNEL: "VOICE_CHANNEL",
} as const;

export const AccordNonForwardingMessageQueue = {
  SOCKET_SUBSCRIPTION: "SOCKET_SUBSCRIPTION",
} as const;
