// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attachment struct {
	ID            uuid.UUID
	ResourceType  string
	Signature     string
	UnixTimestamp int64
	AttachedByID  uuid.UUID
	Linked        bool
	Height        int32
	Width         int32
	Filesize      int32
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type Channel struct {
	ID             uuid.UUID
	Name           string
	Topic          string
	ChannelType    int16
	ParentRoleSync bool
	ParentID       pgtype.UUID
	CreatorID      uuid.UUID
	GuildID        pgtype.UUID
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type ChannelMessage struct {
	ID        uuid.UUID
	Content   string
	IsPinned  bool
	Flags     int32
	UserID    uuid.UUID
	ChannelID uuid.UUID
	GuildID   pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type ChannelMessageAttachment struct {
	ChannelMessageID uuid.UUID
	AttachmentID     uuid.UUID
}

type ChannelUser struct {
	UserID    uuid.UUID
	ChannelID uuid.UUID
}

type Guild struct {
	ID              uuid.UUID
	Name            string
	Description     string
	IsDiscoverable  bool
	ChannelCount    int32
	MemberCount     int32
	CreatorID       uuid.UUID
	GuildCategoryID pgtype.UUID
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
}

type GuildAttachment struct {
	UsageType    int32
	GuildID      uuid.UUID
	AttachmentID uuid.UUID
}

type GuildBan struct {
	UserID    uuid.UUID
	GuildID   uuid.UUID
	Reason    string
	CreatorID uuid.UUID
	BannedAt  pgtype.Timestamp
}

type GuildCategory struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamp
}

type GuildInvite struct {
	ID        uuid.UUID
	Status    int16
	UsedCount int32
	UserID    uuid.UUID
	GuildID   uuid.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type GuildMember struct {
	Nickname  pgtype.Text
	JoinedAt  pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	UserID    uuid.UUID
	GuildID   uuid.UUID
}

type GuildRole struct {
	ID          uuid.UUID
	Name        string
	Permissions int32
	GuildID     uuid.UUID
	CreatorID   uuid.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type GuildRoleChannel struct {
	RoleID    uuid.UUID
	ChannelID uuid.UUID
}

type GuildRoleUser struct {
	RoleID uuid.UUID
	UserID uuid.UUID
}

type OauthAccount struct {
	ID            uuid.UUID
	Email         string
	Provider      string
	ProviderToken string
	ProviderID    string
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type Relationship struct {
	ID        uuid.UUID
	CreatorID uuid.UUID
	Status    int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type RelationshipUser struct {
	RelationshipID uuid.UUID
	UserID         uuid.UUID
}

type User struct {
	ID                uuid.UUID
	Username          string
	DisplayName       string
	PublicFlags       int32
	RelationshipCount int32
	OauthAccountID    uuid.UUID
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}

type UserAttachment struct {
	UserID       uuid.UUID
	AttachmentID uuid.UUID
}

type UserSession struct {
	ID        uuid.UUID
	Token     string
	UserID    uuid.UUID
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type VoiceChannelState struct {
	Mute      bool
	SelfMute  bool
	SelfDeaf  bool
	ChannelID uuid.UUID
	UserID    uuid.UUID
	GuildID   uuid.UUID
}
