// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: user_session.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, token, user_id, expires_at, created_at, updated_at
`

type CreateUserSessionParams struct {
	UserID    uuid.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession, arg.UserID, arg.Token, arg.ExpiresAt)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserSession = `-- name: DeleteUserSession :execrows
DELETE
FROM
user_sessions
WHERE
id = $1
AND
user_id = $2
AND
token != $3
`

type DeleteUserSessionParams struct {
	SessionID uuid.UUID
	UserID    uuid.UUID
	Token     string
}

func (q *Queries) DeleteUserSession(ctx context.Context, arg DeleteUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSession, arg.SessionID, arg.UserID, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getManyUserSessionsByID = `-- name: GetManyUserSessionsByID :many
SELECT
id,
created_at,
expires_at,
(CASE
    WHEN token = $1 THEN true
    ELSE false
END) AS is_current_session
FROM user_sessions
WHERE
user_id = $2
AND
(CASE
    WHEN $3::uuid IS NOT NULL THEN id < $3::uuid
    ELSE TRUE
END)
AND 
(CASE
    WHEN $4::uuid IS NOT NULL THEN id > $4::uuid
    ELSE TRUE
END)
ORDER BY id
LIMIT $5
`

type GetManyUserSessionsByIDParams struct {
	Token        string
	UserID       uuid.UUID
	Before       pgtype.UUID
	After        pgtype.UUID
	ResultsLimit int64
}

type GetManyUserSessionsByIDRow struct {
	ID               uuid.UUID
	CreatedAt        pgtype.Timestamp
	ExpiresAt        pgtype.Timestamp
	IsCurrentSession bool
}

func (q *Queries) GetManyUserSessionsByID(ctx context.Context, arg GetManyUserSessionsByIDParams) ([]GetManyUserSessionsByIDRow, error) {
	rows, err := q.db.Query(ctx, getManyUserSessionsByID,
		arg.Token,
		arg.UserID,
		arg.Before,
		arg.After,
		arg.ResultsLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetManyUserSessionsByIDRow{}
	for rows.Next() {
		var i GetManyUserSessionsByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.IsCurrentSession,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSessionByID = `-- name: GetUserSessionByID :one
SELECT id, token, user_id, expires_at, created_at, updated_at
FROM user_sessions
WHERE id = $1
`

func (q *Queries) GetUserSessionByID(ctx context.Context, sessionID uuid.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByID, sessionID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSessionByToken = `-- name: GetUserSessionByToken :one
SELECT id, token, user_id, expires_at, created_at, updated_at
FROM user_sessions
WHERE token = $1
`

func (q *Queries) GetUserSessionByToken(ctx context.Context, token string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByToken, token)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
