// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: voice_channel_state.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVoiceChannelState = `-- name: CreateVoiceChannelState :one
WITH delete_voice_channel_state AS (
    DELETE FROM
    voice_channel_states
    WHERE
    user_id = $1::uuid
),

insert_voice_channel_state AS (
    INSERT INTO
    voice_channel_states (channel_id, guild_id, user_id)
    SELECT
    c.id,
    c.guild_id,
    $1::uuid
    FROM
    channels c
    WHERE
    c.id = $2::uuid
    RETURNING
    mute,
    self_mute,
    self_deaf,
    channel_id,
    guild_id
)

SELECT
ivcscte.mute, ivcscte.self_mute, ivcscte.self_deaf, ivcscte.channel_id, ivcscte.guild_id,
u.id,
ua.attachment_id,
CASE 
    WHEN gm.nickname IS NOT NULL THEN gm.nickname
    ELSE u.display_name
END::text AS display_name,
u.username,
u.public_flags
FROM guild_members gm, insert_voice_channel_state ivcscte
INNER JOIN users u ON u.id = $1
LEFT JOIN user_attachments ua ON ua.user_id = u.id
`

type CreateVoiceChannelStateParams struct {
	UserID    uuid.UUID
	ChannelID uuid.UUID
}

type CreateVoiceChannelStateRow struct {
	Mute         bool
	SelfMute     bool
	SelfDeaf     bool
	ChannelID    uuid.UUID
	GuildID      uuid.UUID
	ID           uuid.UUID
	AttachmentID pgtype.UUID
	DisplayName  string
	Username     string
	PublicFlags  int32
}

func (q *Queries) CreateVoiceChannelState(ctx context.Context, arg CreateVoiceChannelStateParams) (CreateVoiceChannelStateRow, error) {
	row := q.db.QueryRow(ctx, createVoiceChannelState, arg.UserID, arg.ChannelID)
	var i CreateVoiceChannelStateRow
	err := row.Scan(
		&i.Mute,
		&i.SelfMute,
		&i.SelfDeaf,
		&i.ChannelID,
		&i.GuildID,
		&i.ID,
		&i.AttachmentID,
		&i.DisplayName,
		&i.Username,
		&i.PublicFlags,
	)
	return i, err
}

const deleteVoiceChannelState = `-- name: DeleteVoiceChannelState :exec
DELETE FROM
voice_channel_states
WHERE
user_id = $1
`

func (q *Queries) DeleteVoiceChannelState(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVoiceChannelState, userID)
	return err
}

const updateVoiceChannelState = `-- name: UpdateVoiceChannelState :one
UPDATE voice_channel_states
SET
self_mute = $1,
self_deaf = $2
WHERE
user_id = $3
RETURNING mute, self_mute, self_deaf, channel_id, user_id, guild_id
`

type UpdateVoiceChannelStateParams struct {
	SelfMute bool
	SelfDeaf bool
	UserID   uuid.UUID
}

func (q *Queries) UpdateVoiceChannelState(ctx context.Context, arg UpdateVoiceChannelStateParams) (VoiceChannelState, error) {
	row := q.db.QueryRow(ctx, updateVoiceChannelState, arg.SelfMute, arg.SelfDeaf, arg.UserID)
	var i VoiceChannelState
	err := row.Scan(
		&i.Mute,
		&i.SelfMute,
		&i.SelfDeaf,
		&i.ChannelID,
		&i.UserID,
		&i.GuildID,
	)
	return i, err
}
