version: "3.8"
name: "accord_prod"
services:
  db:
    env_file:
      - .env
    image: accord_postgres
    ports:
      - "5932:5432"
    networks:
      accord_network:
        aliases:
          - db
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  nats:
    env_file:
      - .env
    image: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    networks:
      accord_network:
        aliases:
          - nats
    command: -D -n accord_nats --user accord_nats -pass Lbu8yFEXhKsF7Unq
    restart: always

  frontend:
    env_file:
      - .env
    image: accord_react_frontend
    ports:
      - 3000:80
    networks:
      accord_network:
        aliases:
          - accord_react_frontend
    restart: always

  rest_api:
    env_file:
      - .env
    image: accord_rest_api
    ports:
      - 4000:4000
    networks:
      accord_network:
        aliases:
          - accord_rest
    restart: always

  websocket:
    env_file:
      - .env
    image: accord_websocket_api
    ports:
      - 4001:4001
    networks:
      accord_network:
        aliases:
          - accord_websocket
    restart: always

  voice:
    env_file:
      - .env
    image: accord_voice_server
    ports:
      - 4002:4002
    networks:
      accord_network:
        aliases:
          - accord_voice
    restart: always

volumes:
  db_data:
  mq_data:
networks:
  accord_network:
    name: accord_network
