FROM golang:1.26 as BUILDER

WORKDIR /app

COPY ./backend/go.mod ./
COPY ./backend/go.sum ./

RUN go mod download && go mod verify

COPY ./backend/cmd ./cmd
COPY ./backend/internal ./internal
COPY ./backend/db ./db

RUN go build -v -o /app/init ./cmd/init/...


FROM golang:1.26

WORKDIR /app

COPY --from=BUILDER /app/init ./

## Database ##
ENV DATABASE_URL=

CMD ["/app/init"]
