FROM nginx:alpine

WORKDIR /usr/share/nginx/html

## Env Vars

## Frontend/Backend ##
ENV APP_MODE=
ENV PROTOCOL=
ENV FRONTEND_HOST=

## Cloudinary - Frontend/Backend ##
ENV CLOUDINARY_API_KEY=

## Frontend ##
ENV CLOUDINARY_URL=
ENV CLOUDINARY_RES_URL=

ENV API_URL=
ENV RTC_URL=
ENV WS_URL=

RUN rm -rf /usr/share/nginx/html/*

COPY ./frontend/apps/react-app-v2/dist .
COPY --chmod=0755 /frontend/apps/react-app-v2/*.sh /opt/

RUN rm -rf /etc/nginx/nginx.conf

COPY ./frontend/apps/react-app-v2/nginx.conf /etc/nginx/nginx.conf
RUN chown -R nginx:nginx /usr/share/nginx/html

CMD [ "nginx", "-g", "daemon off;" ]
ENTRYPOINT ["/opt/entrypoint.sh"]
