// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.

package mapper

import (
	goverter "github.com/MikeT117/accord/backend/internal/goverter"
	sqlc "github.com/MikeT117/accord/backend/internal/sqlc"
	models "github.com/MikeT117/accord/backend/models"
	uuid "github.com/google/uuid"
)

type ConverterImpl struct{}

func (c *ConverterImpl) ConverSQLCUserSessionsToUserSession(source sqlc.UserSession) models.UserSession {
	var modelsUserSession models.UserSession
	modelsUserSession.ID = c.uuidUUIDToUuidUUID(source.ID)
	modelsUserSession.Token = source.Token
	modelsUserSession.UserID = c.uuidUUIDToUuidUUID(source.UserID)
	modelsUserSession.CreatedAt = goverter.PGTypeTimestampToTime(source.CreatedAt)
	modelsUserSession.ExpiresAt = goverter.PGTypeTimestampToTime(source.ExpiresAt)
	modelsUserSession.UpdatedAt = goverter.PGTypeTimestampToTime(source.UpdatedAt)
	return modelsUserSession
}
func (c *ConverterImpl) ConverSQLCUserSessionsToUserSessions(source []sqlc.UserSession) []models.UserSession {
	var modelsUserSessionList []models.UserSession
	if source != nil {
		modelsUserSessionList = make([]models.UserSession, len(source))
		for i := 0; i < len(source); i++ {
			modelsUserSessionList[i] = c.ConverSQLCUserSessionsToUserSession(source[i])
		}
	}
	return modelsUserSessionList
}
func (c *ConverterImpl) ConvertGetManyDiscoverableGuildsRowToDiscoverableGuild(source sqlc.GetManyDiscoverableGuildsRow) models.DiscoverableGuild {
	var modelsDiscoverableGuild models.DiscoverableGuild
	modelsDiscoverableGuild.ID = c.uuidUUIDToUuidUUID(source.ID)
	modelsDiscoverableGuild.Name = source.Name
	modelsDiscoverableGuild.Description = source.Description
	modelsDiscoverableGuild.MemberCount = source.MemberCount
	modelsDiscoverableGuild.GuildCategoryID = goverter.PGTypeUUIDToNullableUUID(source.GuildCategoryID)
	modelsDiscoverableGuild.CreatedAt = goverter.PGTypeTimestampToTime(source.CreatedAt)
	modelsDiscoverableGuild.Icon = goverter.PGTypeUUIDToNullableUUID(source.Icon)
	modelsDiscoverableGuild.Banner = goverter.PGTypeUUIDToNullableUUID(source.Banner)
	return modelsDiscoverableGuild
}
func (c *ConverterImpl) ConvertGetManyDiscoverableGuildsRowToDiscoverableGuilds(source []sqlc.GetManyDiscoverableGuildsRow) []models.DiscoverableGuild {
	var modelsDiscoverableGuildList []models.DiscoverableGuild
	if source != nil {
		modelsDiscoverableGuildList = make([]models.DiscoverableGuild, len(source))
		for i := 0; i < len(source); i++ {
			modelsDiscoverableGuildList[i] = c.ConvertGetManyDiscoverableGuildsRowToDiscoverableGuild(source[i])
		}
	}
	return modelsDiscoverableGuildList
}
func (c *ConverterImpl) ConvertGetUserByIDRowToUser(source sqlc.GetUserByIDRow) models.UserLimited {
	var modelsUserLimited models.UserLimited
	modelsUserLimited.ID = c.uuidUUIDToUuidUUID(source.ID)
	modelsUserLimited.Avatar = goverter.PGTypeUUIDToNullableUUID(source.AttachmentID)
	modelsUserLimited.DisplayName = source.DisplayName
	modelsUserLimited.Username = source.Username
	modelsUserLimited.PublicFlags = source.PublicFlags
	return modelsUserLimited
}
func (c *ConverterImpl) ConvertManySQLCGuildInviteToGuildInvite(source []sqlc.GuildInvite) []models.GuildInvite {
	var modelsGuildInviteList []models.GuildInvite
	if source != nil {
		modelsGuildInviteList = make([]models.GuildInvite, len(source))
		for i := 0; i < len(source); i++ {
			modelsGuildInviteList[i] = c.ConvertSQLCGuildInviteToGuildInvite(source[i])
		}
	}
	return modelsGuildInviteList
}
func (c *ConverterImpl) ConvertSQLCChannelToDirectChannel(source sqlc.Channel) models.DirectChannel {
	var modelsDirectChannel models.DirectChannel
	modelsDirectChannel.ID = c.uuidUUIDToUuidUUID(source.ID)
	pString := source.Name
	modelsDirectChannel.Name = &pString
	pString2 := source.Topic
	modelsDirectChannel.Topic = &pString2
	modelsDirectChannel.ChannelType = source.ChannelType
	modelsDirectChannel.CreatorID = c.uuidUUIDToUuidUUID(source.CreatorID)
	modelsDirectChannel.CreatedAt = goverter.PGTypeTimestampToTime(source.CreatedAt)
	modelsDirectChannel.UpdatedAt = goverter.PGTypeTimestampToTime(source.UpdatedAt)
	return modelsDirectChannel
}
func (c *ConverterImpl) ConvertSQLCChannelToGuildChannel(source sqlc.Channel) models.GuildChannel {
	var modelsGuildChannel models.GuildChannel
	modelsGuildChannel.ID = c.uuidUUIDToUuidUUID(source.ID)
	modelsGuildChannel.Name = source.Name
	modelsGuildChannel.Topic = source.Topic
	modelsGuildChannel.ChannelType = source.ChannelType
	modelsGuildChannel.ParentRoleSync = source.ParentRoleSync
	modelsGuildChannel.ParentID = source.ParentID
	modelsGuildChannel.CreatorID = c.uuidUUIDToUuidUUID(source.CreatorID)
	modelsGuildChannel.CreatedAt = goverter.PGTypeTimestampToTime(source.CreatedAt)
	modelsGuildChannel.UpdatedAt = goverter.PGTypeTimestampToTime(source.UpdatedAt)
	return modelsGuildChannel
}
func (c *ConverterImpl) ConvertSQLCCreateChannelMessageRowToMessage(source sqlc.CreateChannelMessageRow) models.ChannelMessage {
	var modelsChannelMessage models.ChannelMessage
	modelsChannelMessage.ID = c.uuidUUIDToUuidUUID(source.ID)
	modelsChannelMessage.ChannelID = c.uuidUUIDToUuidUUID(source.ChannelID)
	modelsChannelMessage.Content = source.Content
	modelsChannelMessage.IsPinned = source.IsPinned
	modelsChannelMessage.Flags = source.Flags
	modelsChannelMessage.CreatedAt = goverter.PGTypeTimestampToTime(source.CreatedAt)
	modelsChannelMessage.UpdatedAt = goverter.ConvertPGTypeTimestampToNullableTime(source.UpdatedAt)
	modelsChannelMessage.Author = goverter.ConvertCreateChannelMessageRowToAuthor(source)
	modelsChannelMessage.Attachments = source.Attachments
	return modelsChannelMessage
}
func (c *ConverterImpl) ConvertSQLCGetManyChannelMessagesByChannelIDRowToMessage(source sqlc.GetManyChannelMessagesByChannelIDRow) models.ChannelMessage {
	var modelsChannelMessage models.ChannelMessage
	modelsChannelMessage.ID = c.uuidUUIDToUuidUUID(source.ID)
	modelsChannelMessage.ChannelID = c.uuidUUIDToUuidUUID(source.ChannelID)
	modelsChannelMessage.Content = source.Content
	modelsChannelMessage.IsPinned = source.IsPinned
	modelsChannelMessage.Flags = source.Flags
	modelsChannelMessage.CreatedAt = goverter.PGTypeTimestampToTime(source.CreatedAt)
	modelsChannelMessage.UpdatedAt = goverter.ConvertPGTypeTimestampToNullableTime(source.UpdatedAt)
	modelsChannelMessage.Author = goverter.ConvertGetManyChannelMessagesByChannelIDRowToAuthor(source)
	modelsChannelMessage.Attachments = source.Attachments
	return modelsChannelMessage
}
func (c *ConverterImpl) ConvertSQLCGetManyChannelMessagesByChannelIDRowsToManyMessage(source []sqlc.GetManyChannelMessagesByChannelIDRow) []models.ChannelMessage {
	var modelsChannelMessageList []models.ChannelMessage
	if source != nil {
		modelsChannelMessageList = make([]models.ChannelMessage, len(source))
		for i := 0; i < len(source); i++ {
			modelsChannelMessageList[i] = c.ConvertSQLCGetManyChannelMessagesByChannelIDRowToMessage(source[i])
		}
	}
	return modelsChannelMessageList
}
func (c *ConverterImpl) ConvertSQLCGetManyGuildBansByGuildIDRowToGuildBan(source sqlc.GetManyGuildBansByGuildIDRow) models.GuildBan {
	var modelsGuildBan models.GuildBan
	pString := source.Reason
	modelsGuildBan.Reason = &pString
	modelsGuildBan.BannedAt = goverter.PGTypeTimestampToTime(source.BannedAt)
	modelsGuildBan.User = goverter.GetManyGuildBansByGuildIDRowToUser(source)
	return modelsGuildBan
}
func (c *ConverterImpl) ConvertSQLCGetManyGuildBansByGuildIDRowToGuildBans(source []sqlc.GetManyGuildBansByGuildIDRow) []models.GuildBan {
	var modelsGuildBanList []models.GuildBan
	if source != nil {
		modelsGuildBanList = make([]models.GuildBan, len(source))
		for i := 0; i < len(source); i++ {
			modelsGuildBanList[i] = c.ConvertSQLCGetManyGuildBansByGuildIDRowToGuildBan(source[i])
		}
	}
	return modelsGuildBanList
}
func (c *ConverterImpl) ConvertSQLCGetManyGuildMembersByGuildIDRowToGuildMember(source sqlc.GetManyGuildMembersByGuildIDRow) models.GuildMemberLimited {
	var modelsGuildMemberLimited models.GuildMemberLimited
	modelsGuildMemberLimited.JoinedAt = goverter.PGTypeTimestampToTime(source.JoinedAt)
	modelsGuildMemberLimited.User = goverter.GetManyGuildMembersByGuildIDRowToUser(source)
	modelsGuildMemberLimited.Roles = source.Roles
	return modelsGuildMemberLimited
}
func (c *ConverterImpl) ConvertSQLCGetManyGuildMembersByGuildIDRowToGuildMembers(source []sqlc.GetManyGuildMembersByGuildIDRow) []models.GuildMemberLimited {
	var modelsGuildMemberLimitedList []models.GuildMemberLimited
	if source != nil {
		modelsGuildMemberLimitedList = make([]models.GuildMemberLimited, len(source))
		for i := 0; i < len(source); i++ {
			modelsGuildMemberLimitedList[i] = c.ConvertSQLCGetManyGuildMembersByGuildIDRowToGuildMember(source[i])
		}
	}
	return modelsGuildMemberLimitedList
}
func (c *ConverterImpl) ConvertSQLCGetManyUsersByIDsRowToUser(source sqlc.GetManyUsersByIDsRow) models.UserLimited {
	var modelsUserLimited models.UserLimited
	modelsUserLimited.ID = c.uuidUUIDToUuidUUID(source.ID)
	modelsUserLimited.Avatar = goverter.PGTypeUUIDToNullableUUID(source.AttachmentID)
	modelsUserLimited.DisplayName = source.DisplayName
	modelsUserLimited.Username = source.Username
	modelsUserLimited.PublicFlags = source.PublicFlags
	return modelsUserLimited
}
func (c *ConverterImpl) ConvertSQLCGetManyUsersByIDsRowToUsers(source []sqlc.GetManyUsersByIDsRow) []models.UserLimited {
	var modelsUserLimitedList []models.UserLimited
	if source != nil {
		modelsUserLimitedList = make([]models.UserLimited, len(source))
		for i := 0; i < len(source); i++ {
			modelsUserLimitedList[i] = c.ConvertSQLCGetManyUsersByIDsRowToUser(source[i])
		}
	}
	return modelsUserLimitedList
}
func (c *ConverterImpl) ConvertSQLCGetUserProfileByIDAndGuildIDRowToUserProfileWithGuildMember(source sqlc.GetUserProfileByIDAndGuildIDRow) models.UserProfileWithGuildMember {
	var modelsUserProfileWithGuildMember models.UserProfileWithGuildMember
	modelsUserProfileWithGuildMember.ID = c.uuidUUIDToUuidUUID(source.ID)
	modelsUserProfileWithGuildMember.DisplayName = source.DisplayName
	modelsUserProfileWithGuildMember.Username = source.Username
	modelsUserProfileWithGuildMember.PublicFlags = source.PublicFlags
	modelsUserProfileWithGuildMember.CreatedAt = goverter.PGTypeTimestampToTime(source.CreatedAt)
	modelsUserProfileWithGuildMember.Avatar = goverter.PGTypeUUIDToNullableUUID(source.AttachmentID)
	modelsUserProfileWithGuildMember.MutualGuilds = source.MutualGuilds
	modelsUserProfileWithGuildMember.GuildMember = c.sqlcGetUserProfileByIDAndGuildIDRowToModelsGuildMemberMinimal(source)
	return modelsUserProfileWithGuildMember
}
func (c *ConverterImpl) ConvertSQLCGetUserProfileByIDRowToUserProfile(source sqlc.GetUserProfileByIDRow) models.UserProfile {
	var modelsUserProfile models.UserProfile
	modelsUserProfile.ID = c.uuidUUIDToUuidUUID(source.ID)
	modelsUserProfile.DisplayName = source.DisplayName
	modelsUserProfile.Username = source.Username
	modelsUserProfile.PublicFlags = source.PublicFlags
	modelsUserProfile.CreatedAt = goverter.PGTypeTimestampToTime(source.CreatedAt)
	modelsUserProfile.Avatar = goverter.PGTypeUUIDToNullableUUID(source.AttachmentID)
	modelsUserProfile.MutualGuilds = source.MutualGuilds
	return modelsUserProfile
}
func (c *ConverterImpl) ConvertSQLCGuildCategoryToGuildCategories(source []sqlc.GuildCategory) []sqlc.GuildCategory {
	return source
}
func (c *ConverterImpl) ConvertSQLCGuildCategoryToGuildCategory(source sqlc.GuildCategory) sqlc.GuildCategory {
	return source
}
func (c *ConverterImpl) ConvertSQLCGuildInviteToGuildInvite(source sqlc.GuildInvite) models.GuildInvite {
	var modelsGuildInvite models.GuildInvite
	modelsGuildInvite.ID = c.uuidUUIDToUuidUUID(source.ID)
	modelsGuildInvite.Status = source.Status
	modelsGuildInvite.UsedCount = source.UsedCount
	modelsGuildInvite.UserID = c.uuidUUIDToUuidUUID(source.UserID)
	modelsGuildInvite.GuildID = c.uuidUUIDToUuidUUID(source.GuildID)
	modelsGuildInvite.CreatedAt = goverter.PGTypeTimestampToTime(source.CreatedAt)
	modelsGuildInvite.UpdatedAt = goverter.PGTypeTimestampToTime(source.UpdatedAt)
	return modelsGuildInvite
}
func (c *ConverterImpl) ConvertSQLCGuildMemberToGuildMember(source sqlc.GuildMember) models.GuildMember {
	var modelsGuildMember models.GuildMember
	modelsGuildMember.Nickname = goverter.ConvertPGTypeTextToNullableString(source.Nickname)
	modelsGuildMember.GuildID = c.uuidUUIDToUuidUUID(source.GuildID)
	modelsGuildMember.JoinedAt = goverter.PGTypeTimestampToTime(source.JoinedAt)
	modelsGuildMember.UpdatedAt = goverter.PGTypeTimestampToTime(source.UpdatedAt)
	return modelsGuildMember
}
func (c *ConverterImpl) ConvertSQLCGuildRoleToGuildRole(source sqlc.GuildRole) models.GuildRole {
	var modelsGuildRole models.GuildRole
	modelsGuildRole.ID = c.uuidUUIDToUuidUUID(source.ID)
	modelsGuildRole.Name = source.Name
	modelsGuildRole.Permissions = source.Permissions
	modelsGuildRole.GuildID = c.uuidUUIDToUuidUUID(source.GuildID)
	modelsGuildRole.CreatorID = c.uuidUUIDToUuidUUID(source.CreatorID)
	modelsGuildRole.CreatedAt = goverter.PGTypeTimestampToTime(source.CreatedAt)
	modelsGuildRole.UpdatedAt = goverter.PGTypeTimestampToTime(source.UpdatedAt)
	return modelsGuildRole
}
func (c *ConverterImpl) ConvertSQLCGuildRoleToGuildRoles(source []sqlc.GuildRole) []models.GuildRole {
	var modelsGuildRoleList []models.GuildRole
	if source != nil {
		modelsGuildRoleList = make([]models.GuildRole, len(source))
		for i := 0; i < len(source); i++ {
			modelsGuildRoleList[i] = c.ConvertSQLCGuildRoleToGuildRole(source[i])
		}
	}
	return modelsGuildRoleList
}
func (c *ConverterImpl) ConvertSQLCGuildToGuild(source sqlc.Guild) models.Guild {
	var modelsGuild models.Guild
	modelsGuild.ID = c.uuidUUIDToUuidUUID(source.ID)
	modelsGuild.Name = source.Name
	modelsGuild.Description = source.Description
	modelsGuild.IsDiscoverable = source.IsDiscoverable
	modelsGuild.CreatorID = c.uuidUUIDToUuidUUID(source.CreatorID)
	modelsGuild.GuildCategoryID = goverter.PGTypeUUIDToNullableUUID(source.GuildCategoryID)
	modelsGuild.ChannelCount = source.ChannelCount
	modelsGuild.MemberCount = source.MemberCount
	modelsGuild.CreatedAt = goverter.PGTypeTimestampToTime(source.CreatedAt)
	modelsGuild.UpdatedAt = goverter.PGTypeTimestampToTime(source.UpdatedAt)
	return modelsGuild
}
func (c *ConverterImpl) ConvertSQLCUpdateChannelMessageRowUpdatedMessage(source sqlc.UpdateChannelMessageRow) models.UpdatedChannelMessage {
	var modelsUpdatedChannelMessage models.UpdatedChannelMessage
	modelsUpdatedChannelMessage.ID = c.uuidUUIDToUuidUUID(source.ID)
	modelsUpdatedChannelMessage.ChannelID = c.uuidUUIDToUuidUUID(source.ChannelID)
	modelsUpdatedChannelMessage.Content = source.Content
	modelsUpdatedChannelMessage.IsPinned = source.IsPinned
	modelsUpdatedChannelMessage.UpdatedAt = goverter.PGTypeTimestampToTime(source.UpdatedAt)
	return modelsUpdatedChannelMessage
}
func (c *ConverterImpl) ConvertSQLUpdateGuildRowToUpdatedGuild(source sqlc.UpdateGuildRow) models.UpdatedGuild {
	var modelsUpdatedGuild models.UpdatedGuild
	modelsUpdatedGuild.Name = source.Name
	modelsUpdatedGuild.Description = source.Description
	modelsUpdatedGuild.IsDiscoverable = source.IsDiscoverable
	modelsUpdatedGuild.Icon = goverter.PGTypeUUIDToNullableUUID(source.Icon)
	modelsUpdatedGuild.Banner = goverter.PGTypeUUIDToNullableUUID(source.Banner)
	modelsUpdatedGuild.GuildCategoryID = goverter.PGTypeUUIDToNullableUUID(source.GuildCategoryID)
	return modelsUpdatedGuild
}
func (c *ConverterImpl) sqlcGetUserProfileByIDAndGuildIDRowToModelsGuildMemberMinimal(source sqlc.GetUserProfileByIDAndGuildIDRow) models.GuildMemberMinimal {
	var modelsGuildMemberMinimal models.GuildMemberMinimal
	modelsGuildMemberMinimal.JoinedAt = goverter.PGTypeTimestampToTime(source.JoinedAt)
	modelsGuildMemberMinimal.Roles = source.Roles
	return modelsGuildMemberMinimal
}
func (c *ConverterImpl) uuidUUIDToUuidUUID(source uuid.UUID) uuid.UUID {
	return source
}
