package entities

const (
	GUILD_OWNER = iota
	GUILD_ADMIN
	MANAGE_GUILD
	MANAGE_GUILD_CHANNELS
	MANAGE_CHANNEL_MESSAGES
	VIEW_GUILD_CHANNEL
	CREATE_CHANNEL_MESSAGE
	CREATE_CHANNEL_PIN
	VIEW_GUILD_MEMBERS
)
