/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAppDashboardRouteRouteImport } from './routes/_auth/app/dashboard/route'
import { Route as AuthAppGuildIdRouteRouteImport } from './routes/_auth/app/$guildId/route'
import { Route as AuthAppDashboardIndexRouteImport } from './routes/_auth/app/dashboard/index'
import { Route as AuthAppGuildIdIndexRouteImport } from './routes/_auth/app/$guildId/index'
import { Route as AuthAppDashboardRequestsRouteImport } from './routes/_auth/app/dashboard/requests'
import { Route as AuthAppDashboardRelationshipsRouteImport } from './routes/_auth/app/dashboard/relationships'
import { Route as AuthAppDashboardBlockedRouteImport } from './routes/_auth/app/dashboard/blocked'
import { Route as AuthAppDashboardChannelIdRouteImport } from './routes/_auth/app/dashboard/$channelId'
import { Route as AuthAppGuildIdChannelIdRouteRouteImport } from './routes/_auth/app/$guildId/$channelId/route'
import { Route as AuthAppGuildIdChannelIdIndexRouteImport } from './routes/_auth/app/$guildId/$channelId/index'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/_auth/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppDashboardRouteRoute = AuthAppDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppGuildIdRouteRoute = AuthAppGuildIdRouteRouteImport.update({
  id: '/$guildId',
  path: '/$guildId',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppDashboardIndexRoute = AuthAppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppDashboardRouteRoute,
} as any)
const AuthAppGuildIdIndexRoute = AuthAppGuildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppGuildIdRouteRoute,
} as any)
const AuthAppDashboardRequestsRoute =
  AuthAppDashboardRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthAppDashboardRouteRoute,
  } as any)
const AuthAppDashboardRelationshipsRoute =
  AuthAppDashboardRelationshipsRouteImport.update({
    id: '/relationships',
    path: '/relationships',
    getParentRoute: () => AuthAppDashboardRouteRoute,
  } as any)
const AuthAppDashboardBlockedRoute = AuthAppDashboardBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AuthAppDashboardRouteRoute,
} as any)
const AuthAppDashboardChannelIdRoute =
  AuthAppDashboardChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => AuthAppDashboardRouteRoute,
  } as any)
const AuthAppGuildIdChannelIdRouteRoute =
  AuthAppGuildIdChannelIdRouteRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => AuthAppGuildIdRouteRoute,
  } as any)
const AuthAppGuildIdChannelIdIndexRoute =
  AuthAppGuildIdChannelIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthAppGuildIdChannelIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/app/$guildId': typeof AuthAppGuildIdRouteRouteWithChildren
  '/app/dashboard': typeof AuthAppDashboardRouteRouteWithChildren
  '/app/$guildId/$channelId': typeof AuthAppGuildIdChannelIdRouteRouteWithChildren
  '/app/dashboard/$channelId': typeof AuthAppDashboardChannelIdRoute
  '/app/dashboard/blocked': typeof AuthAppDashboardBlockedRoute
  '/app/dashboard/relationships': typeof AuthAppDashboardRelationshipsRoute
  '/app/dashboard/requests': typeof AuthAppDashboardRequestsRoute
  '/app/$guildId/': typeof AuthAppGuildIdIndexRoute
  '/app/dashboard/': typeof AuthAppDashboardIndexRoute
  '/app/$guildId/$channelId/': typeof AuthAppGuildIdChannelIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/app/dashboard/$channelId': typeof AuthAppDashboardChannelIdRoute
  '/app/dashboard/blocked': typeof AuthAppDashboardBlockedRoute
  '/app/dashboard/relationships': typeof AuthAppDashboardRelationshipsRoute
  '/app/dashboard/requests': typeof AuthAppDashboardRequestsRoute
  '/app/$guildId': typeof AuthAppGuildIdIndexRoute
  '/app/dashboard': typeof AuthAppDashboardIndexRoute
  '/app/$guildId/$channelId': typeof AuthAppGuildIdChannelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_auth/app/$guildId': typeof AuthAppGuildIdRouteRouteWithChildren
  '/_auth/app/dashboard': typeof AuthAppDashboardRouteRouteWithChildren
  '/_auth/app/$guildId/$channelId': typeof AuthAppGuildIdChannelIdRouteRouteWithChildren
  '/_auth/app/dashboard/$channelId': typeof AuthAppDashboardChannelIdRoute
  '/_auth/app/dashboard/blocked': typeof AuthAppDashboardBlockedRoute
  '/_auth/app/dashboard/relationships': typeof AuthAppDashboardRelationshipsRoute
  '/_auth/app/dashboard/requests': typeof AuthAppDashboardRequestsRoute
  '/_auth/app/$guildId/': typeof AuthAppGuildIdIndexRoute
  '/_auth/app/dashboard/': typeof AuthAppDashboardIndexRoute
  '/_auth/app/$guildId/$channelId/': typeof AuthAppGuildIdChannelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app'
    | '/app/$guildId'
    | '/app/dashboard'
    | '/app/$guildId/$channelId'
    | '/app/dashboard/$channelId'
    | '/app/dashboard/blocked'
    | '/app/dashboard/relationships'
    | '/app/dashboard/requests'
    | '/app/$guildId/'
    | '/app/dashboard/'
    | '/app/$guildId/$channelId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/app'
    | '/app/dashboard/$channelId'
    | '/app/dashboard/blocked'
    | '/app/dashboard/relationships'
    | '/app/dashboard/requests'
    | '/app/$guildId'
    | '/app/dashboard'
    | '/app/$guildId/$channelId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/onboarding'
    | '/_auth/app'
    | '/_auth/app/$guildId'
    | '/_auth/app/dashboard'
    | '/_auth/app/$guildId/$channelId'
    | '/_auth/app/dashboard/$channelId'
    | '/_auth/app/dashboard/blocked'
    | '/_auth/app/dashboard/relationships'
    | '/_auth/app/dashboard/requests'
    | '/_auth/app/$guildId/'
    | '/_auth/app/dashboard/'
    | '/_auth/app/$guildId/$channelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/dashboard': {
      id: '/_auth/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthAppDashboardRouteRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/$guildId': {
      id: '/_auth/app/$guildId'
      path: '/$guildId'
      fullPath: '/app/$guildId'
      preLoaderRoute: typeof AuthAppGuildIdRouteRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/dashboard/': {
      id: '/_auth/app/dashboard/'
      path: '/'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AuthAppDashboardIndexRouteImport
      parentRoute: typeof AuthAppDashboardRouteRoute
    }
    '/_auth/app/$guildId/': {
      id: '/_auth/app/$guildId/'
      path: '/'
      fullPath: '/app/$guildId/'
      preLoaderRoute: typeof AuthAppGuildIdIndexRouteImport
      parentRoute: typeof AuthAppGuildIdRouteRoute
    }
    '/_auth/app/dashboard/requests': {
      id: '/_auth/app/dashboard/requests'
      path: '/requests'
      fullPath: '/app/dashboard/requests'
      preLoaderRoute: typeof AuthAppDashboardRequestsRouteImport
      parentRoute: typeof AuthAppDashboardRouteRoute
    }
    '/_auth/app/dashboard/relationships': {
      id: '/_auth/app/dashboard/relationships'
      path: '/relationships'
      fullPath: '/app/dashboard/relationships'
      preLoaderRoute: typeof AuthAppDashboardRelationshipsRouteImport
      parentRoute: typeof AuthAppDashboardRouteRoute
    }
    '/_auth/app/dashboard/blocked': {
      id: '/_auth/app/dashboard/blocked'
      path: '/blocked'
      fullPath: '/app/dashboard/blocked'
      preLoaderRoute: typeof AuthAppDashboardBlockedRouteImport
      parentRoute: typeof AuthAppDashboardRouteRoute
    }
    '/_auth/app/dashboard/$channelId': {
      id: '/_auth/app/dashboard/$channelId'
      path: '/$channelId'
      fullPath: '/app/dashboard/$channelId'
      preLoaderRoute: typeof AuthAppDashboardChannelIdRouteImport
      parentRoute: typeof AuthAppDashboardRouteRoute
    }
    '/_auth/app/$guildId/$channelId': {
      id: '/_auth/app/$guildId/$channelId'
      path: '/$channelId'
      fullPath: '/app/$guildId/$channelId'
      preLoaderRoute: typeof AuthAppGuildIdChannelIdRouteRouteImport
      parentRoute: typeof AuthAppGuildIdRouteRoute
    }
    '/_auth/app/$guildId/$channelId/': {
      id: '/_auth/app/$guildId/$channelId/'
      path: '/'
      fullPath: '/app/$guildId/$channelId/'
      preLoaderRoute: typeof AuthAppGuildIdChannelIdIndexRouteImport
      parentRoute: typeof AuthAppGuildIdChannelIdRouteRoute
    }
  }
}

interface AuthAppGuildIdChannelIdRouteRouteChildren {
  AuthAppGuildIdChannelIdIndexRoute: typeof AuthAppGuildIdChannelIdIndexRoute
}

const AuthAppGuildIdChannelIdRouteRouteChildren: AuthAppGuildIdChannelIdRouteRouteChildren =
  {
    AuthAppGuildIdChannelIdIndexRoute: AuthAppGuildIdChannelIdIndexRoute,
  }

const AuthAppGuildIdChannelIdRouteRouteWithChildren =
  AuthAppGuildIdChannelIdRouteRoute._addFileChildren(
    AuthAppGuildIdChannelIdRouteRouteChildren,
  )

interface AuthAppGuildIdRouteRouteChildren {
  AuthAppGuildIdChannelIdRouteRoute: typeof AuthAppGuildIdChannelIdRouteRouteWithChildren
  AuthAppGuildIdIndexRoute: typeof AuthAppGuildIdIndexRoute
}

const AuthAppGuildIdRouteRouteChildren: AuthAppGuildIdRouteRouteChildren = {
  AuthAppGuildIdChannelIdRouteRoute:
    AuthAppGuildIdChannelIdRouteRouteWithChildren,
  AuthAppGuildIdIndexRoute: AuthAppGuildIdIndexRoute,
}

const AuthAppGuildIdRouteRouteWithChildren =
  AuthAppGuildIdRouteRoute._addFileChildren(AuthAppGuildIdRouteRouteChildren)

interface AuthAppDashboardRouteRouteChildren {
  AuthAppDashboardChannelIdRoute: typeof AuthAppDashboardChannelIdRoute
  AuthAppDashboardBlockedRoute: typeof AuthAppDashboardBlockedRoute
  AuthAppDashboardRelationshipsRoute: typeof AuthAppDashboardRelationshipsRoute
  AuthAppDashboardRequestsRoute: typeof AuthAppDashboardRequestsRoute
  AuthAppDashboardIndexRoute: typeof AuthAppDashboardIndexRoute
}

const AuthAppDashboardRouteRouteChildren: AuthAppDashboardRouteRouteChildren = {
  AuthAppDashboardChannelIdRoute: AuthAppDashboardChannelIdRoute,
  AuthAppDashboardBlockedRoute: AuthAppDashboardBlockedRoute,
  AuthAppDashboardRelationshipsRoute: AuthAppDashboardRelationshipsRoute,
  AuthAppDashboardRequestsRoute: AuthAppDashboardRequestsRoute,
  AuthAppDashboardIndexRoute: AuthAppDashboardIndexRoute,
}

const AuthAppDashboardRouteRouteWithChildren =
  AuthAppDashboardRouteRoute._addFileChildren(
    AuthAppDashboardRouteRouteChildren,
  )

interface AuthAppRouteRouteChildren {
  AuthAppGuildIdRouteRoute: typeof AuthAppGuildIdRouteRouteWithChildren
  AuthAppDashboardRouteRoute: typeof AuthAppDashboardRouteRouteWithChildren
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppGuildIdRouteRoute: AuthAppGuildIdRouteRouteWithChildren,
  AuthAppDashboardRouteRoute: AuthAppDashboardRouteRouteWithChildren,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
