/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAppGuildIdRouteRouteImport } from './routes/_auth/app/$guildId/route'
import { Route as AuthAppHomeIndexRouteImport } from './routes/_auth/app/home/index'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/_auth/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppGuildIdRouteRoute = AuthAppGuildIdRouteRouteImport.update({
  id: '/$guildId',
  path: '/$guildId',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppHomeIndexRoute = AuthAppHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/app/$guildId': typeof AuthAppGuildIdRouteRoute
  '/app/home': typeof AuthAppHomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/app/$guildId': typeof AuthAppGuildIdRouteRoute
  '/app/home': typeof AuthAppHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_auth/app/$guildId': typeof AuthAppGuildIdRouteRoute
  '/_auth/app/home/': typeof AuthAppHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/app' | '/app/$guildId' | '/app/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/app' | '/app/$guildId' | '/app/home'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/_auth/app'
    | '/_auth/app/$guildId'
    | '/_auth/app/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/$guildId': {
      id: '/_auth/app/$guildId'
      path: '/$guildId'
      fullPath: '/app/$guildId'
      preLoaderRoute: typeof AuthAppGuildIdRouteRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/home/': {
      id: '/_auth/app/home/'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AuthAppHomeIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppGuildIdRouteRoute: typeof AuthAppGuildIdRouteRoute
  AuthAppHomeIndexRoute: typeof AuthAppHomeIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppGuildIdRouteRoute: AuthAppGuildIdRouteRoute,
  AuthAppHomeIndexRoute: AuthAppHomeIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
