// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	Errors: {
		/**
		 * E​r​r​o​r​ ​d​u​r​i​n​g​ ​l​o​g​i​n​:​ ​{​e​r​r​o​r​}
		 * @param {string} error
		 */
		Login: RequiredParams<'error'>
	}
	Actions: {
		/**
		 * S​i​g​n​ ​I​n​ ​w​i​t​h​ ​{​p​r​o​v​i​d​e​r​}
		 * @param {string} provider
		 */
		SignInWith: RequiredParams<'provider'>
		/**
		 * C​a​n​c​e​l
		 */
		Cancel: string
		/**
		 * D​e​l​e​t​e
		 */
		Delete: string
		/**
		 * D​i​s​c​o​n​n​e​c​t
		 */
		Disconnect: string
		/**
		 * G​o​ ​B​a​c​k
		 */
		GoBack: string
		/**
		 * B​a​c​k
		 */
		Back: string
		/**
		 * A​t​t​a​c​h​ ​F​i​l​e
		 */
		AttachFile: string
		/**
		 * O​p​e​n​ ​E​m​o​j​i​ ​S​e​l​e​c​t​o​r
		 */
		OpenEmojiSelector: string
		/**
		 * S​y​n​c
		 */
		Sync: string
		/**
		 * D​e​l​e​t​e​ ​C​h​a​n​n​e​l
		 */
		DeleteChannel: string
		/**
		 * D​e​l​e​t​e​ ​C​a​t​e​g​o​r​y
		 */
		DeleteCategory: string
		/**
		 * C​r​e​a​t​e​ ​C​h​a​n​n​e​l
		 */
		CreateChannel: string
		/**
		 * C​r​e​a​t​e​ ​C​a​t​e​g​o​r​y
		 */
		CreateCategory: string
		/**
		 * C​r​e​a​t​e​ ​I​n​v​i​t​e
		 */
		CreateInvite: string
		/**
		 * M​u​t​e
		 */
		Mute: string
		/**
		 * U​n​m​u​t​e
		 */
		Unmute: string
		/**
		 * L​e​a​v​e​ ​S​e​r​v​e​r
		 */
		LeaveServer: string
		/**
		 * B​a​n
		 */
		Ban: string
		/**
		 * J​o​i​n
		 */
		Join: string
		/**
		 * C​r​e​a​t​e
		 */
		Create: string
		/**
		 * N​e​x​t
		 */
		Next: string
		/**
		 * S​e​n​d​ ​I​n​v​i​t​e
		 */
		SendInvite: string
		/**
		 * C​o​p​y​ ​I​n​v​i​t​e
		 */
		CopyInvite: string
		/**
		 * C​h​a​n​g​e​ ​B​a​n​n​e​r
		 */
		ChangeBanner: string
		/**
		 * U​n​b​a​n
		 */
		Unban: string
		/**
		 * D​e​l​e​t​e​ ​I​n​v​i​t​e
		 */
		DeleteInvite: string
		/**
		 * B​a​n​ ​{​d​i​s​p​l​a​y​N​a​m​e​}
		 * @param {string} displayName
		 */
		BanMember: RequiredParams<'displayName'>
		/**
		 * K​i​c​k​ ​{​d​i​s​p​l​a​y​N​a​m​e​}
		 * @param {string} displayName
		 */
		KickMember: RequiredParams<'displayName'>
		/**
		 * A​d​d​ ​M​e​m​b​e​r
		 */
		AddMember: string
		/**
		 * A​s​s​i​g​n
		 */
		Assign: string
		/**
		 * C​r​e​a​t​e​ ​R​o​l​e
		 */
		CreateRole: string
		/**
		 * D​e​l​e​t​e​ ​S​e​r​v​e​r
		 */
		DeleteServer: string
		/**
		 * S​e​n​d​ ​R​e​q​u​e​s​t
		 */
		SendRequest: string
		/**
		 * D​e​l​e​t​e​ ​A​c​c​o​u​n​t
		 */
		DeleteAccount: string
		/**
		 * L​o​g​ ​O​u​t
		 */
		LogOut: string
		/**
		 * R​e​s​e​t
		 */
		Reset: string
		/**
		 * S​a​v​e
		 */
		Save: string
		/**
		 * R​e​l​o​a​d
		 */
		Reload: string
	}
	Tooltips: {
		/**
		 * N​a​v​i​g​a​t​e​ ​t​o​:​ ​{​g​u​i​l​d​N​a​m​e​}
		 * @param {string} guildName
		 */
		NavigateToGuild: RequiredParams<'guildName'>
		/**
		 * U​s​e​r​ ​D​a​s​h​b​o​a​r​d
		 */
		UserDashboard: string
		/**
		 * C​r​e​a​t​e​ ​S​e​r​v​e​r
		 */
		CreateServer: string
		/**
		 * P​u​b​l​i​c​ ​S​e​r​v​e​r​s
		 */
		PublicServers: string
		/**
		 * U​s​e​r​ ​S​e​t​t​i​n​g​s
		 */
		UserSettings: string
		/**
		 * P​i​n​n​e​d​ ​M​e​s​s​a​g​e​s
		 */
		PinnedMessages: string
		/**
		 * B​a​n​ ​A​c​t​i​o​n​s
		 */
		BanActions: string
		/**
		 * I​n​v​i​t​e​ ​A​c​t​i​o​n​s
		 */
		InviteActions: string
		/**
		 * M​e​m​b​e​r​ ​A​c​t​i​o​n​s
		 */
		MemberActions: string
		/**
		 * C​r​e​a​t​e​ ​N​e​w​ ​R​o​l​e
		 */
		CreateRole: string
		/**
		 * '​B​a​c​k​ ​t​o​ ​O​v​e​r​v​i​e​w​'
		 */
		BackToOverview: string
		/**
		 * E​d​i​t​ ​R​o​l​e
		 */
		EditRole: string
		/**
		 * D​e​l​e​t​e​ ​R​o​l​e
		 */
		DeleteRole: string
		/**
		 * U​n​a​s​s​i​g​n​ ​F​r​o​m​ ​R​o​l​e
		 */
		UnassignFromRole: string
		/**
		 * M​e​s​s​a​g​e​ ​{​d​i​s​p​l​a​y​N​a​m​e​}
		 * @param {string} displayName
		 */
		MessageUser: RequiredParams<'displayName'>
		/**
		 * M​e​s​s​a​g​e​ ​{​d​i​s​p​l​a​y​N​a​m​e​}
		 * @param {string} displayName
		 */
		UnfriendUser: RequiredParams<'displayName'>
		/**
		 * M​e​s​s​a​g​e​ ​{​d​i​s​p​l​a​y​N​a​m​e​}
		 * @param {string} displayName
		 */
		UnblockUser: RequiredParams<'displayName'>
		/**
		 * A​c​c​e​p​t​ ​{​d​i​s​p​l​a​y​N​a​m​e​}​'​s​ ​r​e​q​u​e​s​t
		 * @param {string} displayName
		 */
		AcceptUserRequest: RequiredParams<'displayName'>
		/**
		 * D​e​c​l​i​n​e​ ​{​d​i​s​p​l​a​y​N​a​m​e​}​'​s​ ​r​e​q​u​e​s​t
		 * @param {string} displayName
		 */
		DeclineUserRequest: RequiredParams<'displayName'>
		/**
		 * C​a​n​c​e​l​ ​r​e​q​u​e​s​t​ ​t​o​ ​{​d​i​s​p​l​a​y​N​a​m​e​}
		 * @param {string} displayName
		 */
		CancelUserRequest: RequiredParams<'displayName'>
		/**
		 * D​e​l​e​t​e​ ​S​e​s​s​i​o​n
		 */
		DeleteSession: string
		/**
		 * A​l​l​ ​R​o​l​e​s
		 */
		AllRoles: string
	}
	Selects: {
		Placeholders: {
			/**
			 * S​e​l​e​c​t​ ​a​ ​c​a​t​e​g​o​r​y
			 */
			SelectCategory: string
		}
	}
	Hints: {
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​{​t​y​p​e​}​ ​t​h​i​s​ ​{​s​u​b​j​e​c​t​}​,​ ​t​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​?
		 * @param {string} subject
		 * @param {string} type
		 */
		DeletetionWarning: RequiredParams<'subject' | 'type'>
		/**
		 * P​e​r​m​i​s​s​i​o​n​s​ ​f​o​r​ ​t​h​i​s​ ​c​h​a​n​n​e​l​ ​a​r​e​ ​s​y​n​c​e​d​ ​w​i​t​h​ ​t​h​e​ ​p​a​r​e​n​t​ ​c​a​t​e​g​o​r​y​.
		 */
		PermissionsSynced: string
		/**
		 * P​e​r​m​i​s​s​i​o​n​s​ ​a​r​e​ ​n​o​t​ ​s​y​n​c​e​d​ ​w​i​t​h​ ​C​a​t​e​g​o​r​y
		 */
		PermissionsUnsynced: string
		/**
		 * U​s​e​r​s​ ​w​i​t​h​ ​'​M​a​n​a​g​e​ ​M​e​s​s​a​g​e​s​'​ ​c​a​n​ ​p​i​n​ ​m​e​s​s​a​g​e​s
		 */
		PinMessages: string
		/**
		 * T​h​i​s​ ​c​h​a​n​n​e​l​ ​d​o​e​s​n​'​t​ ​h​a​v​e​ ​a​n​y​ ​p​i​n​n​e​d​ ​m​e​s​s​a​g​e​s​.​.​.​ ​y​e​t​!
		 */
		NoPinnedMessages: string
		/**
		 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​b​a​n​ ​{​d​i​s​p​l​a​y​N​a​m​e​}​,​ ​t​h​e​y​ ​w​o​n​'​t​ ​b​e​ ​a​b​l​e​ ​t​o​ ​r​e​t​u​r​n​ ​u​n​l​e​s​s​
	​ ​ ​ ​ ​ ​ ​ ​ ​u​n​b​a​n​n​e​d​.
		 * @param {string} displayName
		 */
		BanUser: RequiredParams<'displayName'>
		/**
		 * S​e​n​d​i​n​g​.​.​.
		 */
		InviteSending: string
		/**
		 * I​n​v​i​t​e​ ​S​e​n​t
		 */
		InviteSent: string
		/**
		 * I​n​v​i​t​e​ ​F​a​i​l​e​d
		 */
		InviteFailed: string
		/**
		 * A​p​p​l​i​e​s​ ​t​o​ ​a​l​l​ ​m​e​m​b​e​r​s​ ​o​f​ ​t​h​i​s​ ​s​e​r​v​e​r
		 */
		DefaultRole: string
		/**
		 * Y​o​u​r​ ​d​i​s​p​l​a​y​ ​n​a​m​e​ ​i​s​ ​v​i​s​i​b​l​e​ ​t​o​ ​e​v​e​r​y​o​n​e​.
		 */
		DisplayName: string
		/**
		 * D​e​l​e​t​i​n​g​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
		 */
		AccountDeletion: string
		/**
		 * C​a​r​e​f​u​l​ ​-​ ​Y​o​u​ ​h​a​v​e​ ​u​n​s​a​v​e​d​ ​c​h​a​n​g​e​s​!
		 */
		UnsavedChanges: string
		/**
		 * A​c​c​o​r​d​ ​e​n​c​o​u​n​t​e​r​e​d​ ​a​n​ ​e​r​r​o​r​,​ ​s​e​e​ ​t​h​e​ ​c​o​n​s​o​l​e​ ​f​o​r​ ​t​e​c​h​n​i​c​a​l​ ​d​e​t​a​i​l​s​.
		 */
		Error: string
	}
	Permissions: {
		Titles: {
			/**
			 * V​i​e​w​ ​C​h​a​n​n​e​l
			 */
			ViewChannel: string
			/**
			 * M​a​n​a​g​e​ ​C​h​a​n​n​e​l​s
			 */
			ManageChannels: string
			/**
			 * S​e​n​d​ ​M​e​s​s​a​g​e​s
			 */
			SendMessages: string
			/**
			 * M​a​n​a​g​e​ ​M​e​s​s​a​g​e​s
			 */
			ManageMessages: string
			/**
			 * M​a​n​a​g​e​ ​G​u​i​l​d
			 */
			ManageGuild: string
			/**
			 * G​u​i​l​d​ ​A​d​m​i​n
			 */
			GuildAdmin: string
		}
		Descriptions: {
			/**
			 * A​l​l​o​w​s​ ​u​s​e​r​s​ ​t​o​ ​v​i​e​w​ ​c​h​a​n​n​e​l​s​.
			 */
			ViewChannel: string
			/**
			 * A​l​l​o​w​s​ ​m​e​m​b​e​r​s​ ​t​o​ ​c​r​e​a​t​e​,​ ​m​o​d​i​f​y​ ​o​r​ ​d​e​l​e​t​e​ ​c​h​a​n​n​e​l​s​.
			 */
			ManageChannels: string
			/**
			 * A​l​l​o​w​s​ ​u​s​e​r​s​ ​t​o​ ​s​e​n​d​ ​m​e​s​s​a​g​e​s​ ​w​i​t​h​i​n​ ​c​h​a​n​n​e​l​s
			 */
			SendMessages: string
			/**
			 * A​l​l​o​w​s​ ​u​s​e​r​s​ ​t​o​ ​m​a​n​a​g​e​ ​m​e​s​s​a​g​e​s​ ​(​i​n​c​l​u​d​i​n​g​ ​o​t​h​e​r​ ​m​e​m​b​e​r​s​ ​m​e​s​s​a​g​e​s​)​ ​i​n​ ​c​h​a​n​n​e​l​s
			 */
			ManageMessages: string
			/**
			 * A​l​l​o​w​s​ ​u​s​e​r​s​ ​t​o​ ​m​a​n​a​g​e​r​ ​t​h​e​ ​s​e​r​v​e​r​,​ ​c​r​e​a​t​e​ ​c​h​a​n​n​e​l​s​,​ ​r​o​l​e​s​ ​e​t​c​.
			 */
			ManageGuild: string
			/**
			 * I​n​ ​a​d​d​i​t​i​o​n​ ​t​o​ ​a​l​l​ ​o​t​h​e​r​ ​p​e​r​m​i​s​s​i​o​n​s​,​ ​u​s​e​r​s​ ​m​a​y​ ​b​a​n​/​u​n​b​a​n​ ​u​s​e​r​s​.
			 */
			GuildAdmin: string
		}
	}
	Toggles: {
		Labels: {
			/**
			 * A​l​l​o​w​ ​f​r​i​e​n​d​ ​r​e​q​u​e​s​t​s
			 */
			AllowFriendRequests: string
			/**
			 * A​l​l​o​w​ ​s​e​r​v​e​r​ ​m​e​m​b​e​r​ ​D​M​s
			 */
			AllowServerMemberDMs: string
			/**
			 * D​i​s​c​o​v​e​r​a​b​l​e
			 */
			Discoverable: string
			/**
			 * P​r​i​v​a​t​e​ ​C​h​a​n​n​e​l
			 */
			PrivateChannel: string
			/**
			 * P​r​i​v​a​t​e​ ​C​a​t​e​g​o​r​y
			 */
			PrivateCategory: string
		}
		HelperText: {
			/**
			 * A​l​l​o​w​ ​u​s​e​r​s​ ​t​o​ ​s​e​n​d​ ​f​r​i​e​n​d​ ​r​e​q​u​e​s​t​s
			 */
			AllowFriendRequests: string
			/**
			 * A​l​l​o​w​ ​m​e​m​b​e​r​s​ ​o​f​ ​s​e​r​v​e​r​s​ ​y​o​u​ ​h​a​v​e​ ​j​o​i​n​e​d​ ​s​e​n​d​ ​y​o​u​ ​m​e​s​s​a​g​e​s
			 */
			AllowServerMemberDMs: string
			/**
			 * S​e​t​ ​s​e​r​v​e​r​ ​v​i​s​i​b​i​l​i​t​y​ ​i​n​ ​s​e​r​v​e​r​ ​b​r​o​w​s​e​r
			 */
			Discoverable: string
			/**
			 * R​e​s​t​r​i​c​t​ ​c​h​a​n​n​e​l​ ​t​o​ ​s​p​e​c​i​f​i​c​ ​r​o​l​e​s
			 */
			RestrictChannel: string
			/**
			 * R​e​s​t​r​i​c​t​ ​c​a​t​e​g​o​r​y​ ​t​o​ ​s​p​e​c​i​f​i​c​ ​r​o​l​e​s
			 */
			RestrictCategory: string
		}
	}
	Inputs: {
		Placeholders: {
			/**
			 * F​i​l​t​e​r​ ​R​e​q​u​e​s​t​s
			 */
			FilterRequests: string
			/**
			 * F​i​l​t​e​r​ ​F​r​i​e​n​d​s
			 */
			FilterFriends: string
			/**
			 * F​i​l​t​e​r​ ​B​a​n​s
			 */
			FilterBans: string
			/**
			 * F​i​l​t​e​r​ ​R​o​l​e​s
			 */
			FilterRoles: string
			/**
			 * F​i​l​t​e​r​ ​M​e​m​b​e​r​s
			 */
			FilterMembers: string
			/**
			 * F​i​l​t​e​r​ ​B​l​o​c​k​s
			 */
			FilterBlocks: string
			/**
			 * F​i​l​t​e​r​ ​S​e​r​v​e​r​s
			 */
			FilterServers: string
			/**
			 * E​n​t​e​r​ ​a​ ​n​a​m​e
			 */
			EnterName: string
			/**
			 * E​n​t​e​r​ ​a​ ​u​s​e​r​n​a​m​e
			 */
			EnterUsername: string
			/**
			 * E​n​t​e​r​ ​a​ ​t​o​p​i​c
			 */
			EnterTopic: string
			/**
			 * R​e​a​s​o​n​ ​f​o​r​ ​b​a​n
			 */
			BanReason: string
			/**
			 * S​e​a​r​c​h​ ​f​o​r​ ​s​e​r​v​e​r​s​.​.​.
			 */
			SearchServers: string
			/**
			 * S​e​a​r​c​h​ ​f​o​r​ ​f​r​i​e​n​d​s​.​.​.
			 */
			SearchFriends: string
			/**
			 * C​h​a​n​n​e​l​ ​n​a​m​e
			 */
			ChannelName: string
			/**
			 * C​h​a​n​n​e​l​ ​t​o​p​i​c
			 */
			ChannelTopic: string
			/**
			 * C​a​t​e​g​o​r​y​ ​n​a​m​e
			 */
			CategoryName: string
			/**
			 * G​i​v​e​ ​y​o​u​r​ ​s​e​r​v​e​r​ ​a​ ​n​a​m​e
			 */
			ServerName: string
			/**
			 * W​h​a​t​'​s​ ​y​o​u​r​ ​s​e​r​v​e​r​ ​a​b​o​u​t​?
			 */
			ServerDescription: string
			/**
			 * W​r​i​t​e​ ​a​ ​m​e​s​s​a​g​e​.​.​.
			 */
			GrantedWriteMessage: string
			/**
			 * Y​o​u​ ​a​r​e​ ​n​o​t​ ​p​e​r​m​i​t​t​e​d​ ​t​o​ ​p​o​s​t​ ​i​n​ ​t​h​i​s​ ​c​h​a​n​n​e​l
			 */
			DeniedWriteMessage: string
		}
		Labels: {
			/**
			 * E​n​t​e​r​ ​t​h​e​ ​{​s​u​b​j​e​c​t​}​ ​n​a​m​e​ ​b​e​l​o​w​ ​t​o​ ​c​o​n​f​i​r​m​.
			 * @param {string} subject
			 */
			DeletionConfirmation: RequiredParams<'subject'>
			/**
			 * D​i​s​p​l​a​y​ ​N​a​m​e
			 */
			DisplayName: string
			/**
			 * U​s​e​r​n​a​m​e
			 */
			Username: string
			/**
			 * S​e​r​v​e​r​ ​D​e​s​c​r​i​p​t​i​o​n
			 */
			ServerDescription: string
			/**
			 * S​e​r​v​e​r​ ​N​a​m​e
			 */
			ServerName: string
			/**
			 * C​h​a​n​n​e​l​ ​N​a​m​e
			 */
			ChannelName: string
			/**
			 * C​a​t​e​g​o​r​y​ ​N​a​m​e
			 */
			CategoryName: string
			/**
			 * C​h​a​n​n​e​l​ ​T​o​p​i​c
			 */
			ChannelTopic: string
		}
	}
	RadioGroups: {
		Names: {
			/**
			 * T​e​x​t
			 */
			Text: string
			/**
			 * V​o​i​c​e
			 */
			Voice: string
		}
		Descriptions: {
			/**
			 * S​e​n​d​ ​m​e​s​s​a​g​e​s​,​ ​i​m​a​g​e​s​,​ ​e​m​o​j​i​ ​e​t​c​.
			 */
			Text: string
			/**
			 * V​o​i​c​e​ ​c​h​a​t​ ​w​i​t​h​ ​f​r​i​e​n​d​s​.
			 */
			Voice: string
		}
	}
	Tables: {
		Heads: {
			/**
			 * I​d
			 */
			ID: string
			/**
			 * E​x​p​i​r​e​s
			 */
			Expires: string
			/**
			 * C​u​r​r​e​n​t​ ​S​e​s​s​i​o​n
			 */
			CurrentSession: string
			/**
			 * U​s​e​r
			 */
			User: string
			/**
			 * B​a​n​n​e​d
			 */
			Banned: string
			/**
			 * R​e​a​s​o​n
			 */
			Reason: string
			/**
			 * A​c​t​i​o​n​s
			 */
			Actions: string
			/**
			 * C​r​e​a​t​o​r
			 */
			Creator: string
			/**
			 * C​r​e​a​t​e​d
			 */
			Created: string
			/**
			 * U​s​e​s
			 */
			Uses: string
			/**
			 * N​a​m​e
			 */
			Name: string
			/**
			 * M​e​m​b​e​r​ ​S​i​n​c​e
			 */
			MemberSince: string
			/**
			 * J​o​i​n​e​d​ ​A​c​c​o​r​d
			 */
			JoinedAccord: string
			/**
			 * I​s​ ​C​r​e​a​t​o​r
			 */
			IsCreator: string
			/**
			 * R​o​l​e​s
			 */
			Roles: string
		}
	}
	General: {
		/**
		 * O​u​t​g​o​i​n​g​ ​R​e​q​u​e​s​t
		 */
		OutgoingRequest: string
		/**
		 * I​n​c​o​m​i​n​g​ ​R​e​q​u​e​s​t
		 */
		IncomingRequest: string
		/**
		 * C​u​s​t​o​m​ ​R​o​l​e​s
		 */
		CustomRoles: string
		/**
		 * D​e​f​a​u​l​t​ ​P​e​r​m​i​s​s​i​o​n​s
		 */
		DefaultPermissions: string
		/**
		 * R​o​l​e​s
		 */
		Roles: string
		/**
		 * E​d​i​t​ ​R​o​l​e​ ​-​ ​{​r​o​l​e​N​a​m​e​}
		 * @param {string} roleName
		 */
		EditRole: RequiredParams<'roleName'>
		/**
		 * M​e​m​b​e​r​s
		 */
		Members: string
		/**
		 * S​e​r​v​e​r​ ​M​e​m​b​e​r​s
		 */
		ServerMembers: string
		/**
		 * I​n​v​i​t​e​s
		 */
		Invites: string
		/**
		 * S​e​r​v​e​r​ ​B​a​n​s
		 */
		ServerBans: string
		/**
		 * S​e​r​v​e​r​ ​B​a​n​n​e​r
		 */
		ServerBanner: string
		/**
		 * D​i​s​p​l​a​y
		 */
		Display: string
		/**
		 * S​e​r​v​e​r​ ​C​a​t​e​g​o​r​y
		 */
		ServerCategory: string
		/**
		 * C​r​e​a​t​e​ ​S​e​r​v​e​r
		 */
		CreateServer: string
		/**
		 * C​h​a​n​n​e​l​ ​T​y​p​e
		 */
		ChannelType: string
		/**
		 * H​o​m​e
		 */
		Home: string
		/**
		 * D​i​s​c​o​v​e​r
		 */
		Discover: string
		/**
		 * D​i​s​c​o​v​e​r​y
		 */
		Discovery: string
		/**
		 * Q​u​e​r​y​:​ ​{​q​u​e​r​y​}
		 * @param {string} query
		 */
		Query: RequiredParams<'query'>
		/**
		 * {​c​o​u​n​t​}​ ​M​e​m​b​e​r​s​(​s​)
		 * @param {number} count
		 */
		GuildMemberCount: RequiredParams<'count'>
		/**
		 * {​c​o​u​n​t​}​ ​F​r​i​e​n​d​s
		 * @param {number} count
		 */
		FriendCount: RequiredParams<'count'>
		/**
		 * S​e​r​v​e​r​ ​R​o​l​e​s
		 */
		ServerRoles: string
		/**
		 * A​s​s​i​g​n​e​d​ ​R​o​l​e​s​ ​-​ ​{​c​o​u​n​t​}
		 * @param {number} count
		 */
		AssignedRoles: RequiredParams<'count'>
		/**
		 * O​v​e​r​v​i​e​w
		 */
		Overview: string
		/**
		 * P​e​r​m​i​s​s​i​o​n​s
		 */
		Permissions: string
		/**
		 * D​a​n​g​e​r​ ​Z​o​n​e
		 */
		DangerZone: string
		/**
		 * V​o​i​c​e​ ​C​o​n​n​e​c​t​e​d
		 */
		VoiceConnected: string
		/**
		 * N​o​t​ ​F​o​u​n​d​!
		 */
		NotFound: string
		/**
		 * P​i​n​n​e​d​ ​M​e​s​s​a​g​e​s
		 */
		PinnedMessages: string
		/**
		 * C​h​a​n​n​e​l​ ​S​e​t​t​i​n​g​s
		 */
		ChannelSettings: string
		/**
		 * C​a​t​e​g​o​r​y​ ​S​e​t​t​i​n​g​s
		 */
		CategorySettings: string
		/**
		 * S​e​r​v​e​r​ ​S​e​t​t​i​n​g​s
		 */
		ServerSettings: string
		/**
		 * B​a​n​ ​U​s​e​r
		 */
		BanUser: string
		/**
		 * F​i​n​d​ ​y​o​u​r​ ​c​o​m​m​u​n​i​t​y​ ​o​n​ ​A​c​c​o​r​d
		 */
		FindCommunity: string
		/**
		 * F​r​o​m​ ​g​a​m​i​n​g​,​ ​t​o​ ​m​u​s​i​c​,​ ​t​o​ ​l​e​a​r​n​i​n​g​,​ ​t​h​e​r​e​'​s​ ​a​ ​p​l​a​c​e​ ​f​o​r​ ​y​o​u​.
		 */
		Community: string
		/**
		 * P​o​p​u​l​a​r​ ​C​o​m​m​u​n​i​t​i​e​s
		 */
		PopularCommunities: string
		/**
		 * J​o​i​n​e​d
		 */
		Joined: string
		/**
		 * S​e​n​d​ ​i​n​v​i​t​e​ ​t​o​ ​f​r​i​e​n​d​s
		 */
		SendInviteToFriends: string
		/**
		 * O​r​ ​c​o​p​y​ ​a​n​ ​i​n​v​i​t​e​ ​l​i​n​k​ ​t​o​ ​p​a​s​t​e​ ​e​l​s​e​w​h​e​r​e
		 */
		CopyInviteLink: string
		/**
		 * T​h​i​s​ ​i​m​a​g​e​ ​w​i​l​l​ ​d​i​s​p​l​a​y​ ​a​t​ ​t​h​e​ ​t​o​p​ ​o​f​ ​y​o​u​r​ ​c​h​a​n​n​e​l​s​ ​l​i​s​t​.
		 */
		ImageDisplay: string
		/**
		 * A​s​s​i​g​n​ ​M​e​m​b​e​r​s
		 */
		AssignMembers: string
		/**
		 * R​o​l​e​ ​N​a​m​e
		 */
		RoleName: string
		/**
		 * U​s​e​r​ ​M​a​n​a​g​e​m​e​n​t
		 */
		UserManagement: string
		/**
		 * A​d​d​ ​F​r​i​e​n​d
		 */
		AddFriend: string
		/**
		 * F​r​i​e​n​d​s
		 */
		Friends: string
		/**
		 * R​e​q​u​e​s​t​s
		 */
		Requests: string
		/**
		 * B​l​o​c​k​e​d
		 */
		Blocked: string
		/**
		 * D​i​r​e​c​t​ ​M​e​s​s​a​g​e​s
		 */
		DirectMessages: string
		/**
		 * G​r​o​u​p​ ​C​h​a​n​n​e​l
		 */
		GroupChannel: string
		/**
		 * S​e​r​v​e​r​s​ ​M​a​n​a​g​e​r
		 */
		ServersManager: string
		/**
		 * Y​e​s
		 */
		Yes: string
		/**
		 * N​o
		 */
		No: string
		/**
		 * M​y​ ​A​c​c​o​u​n​t
		 */
		MyAccount: string
		/**
		 * F​r​i​e​n​d​ ​R​e​q​u​e​s​t​s
		 */
		FriendRequests: string
		/**
		 * A​c​c​o​u​n​t​ ​D​e​l​e​t​i​o​n
		 */
		AccountDeletion: string
		/**
		 * S​e​r​v​e​r​ ​P​r​i​v​a​c​y
		 */
		ServerPrivacy: string
		/**
		 * S​e​s​s​i​o​n​s​ ​M​a​n​a​g​e​r
		 */
		SessionsManager: string
		/**
		 * U​s​e​r​ ​S​e​t​t​i​n​g​s
		 */
		UserSettings: string
		/**
		 * S​e​r​v​e​r​s
		 */
		Servers: string
		/**
		 * S​e​s​s​i​o​n​s
		 */
		Sessions: string
		/**
		 * R​o​l​e​s​ ​-​ ​{​c​o​u​n​t​}
		 * @param {number} count
		 */
		RolesCount: RequiredParams<'count'>
		/**
		 * M​e​m​b​e​r​ ​S​i​n​c​e
		 */
		MemberSince: string
		/**
		 * A​c​c​o​r​d​ ​M​e​m​b​e​r​ ​S​i​n​c​e
		 */
		AccordMemberSince: string
		/**
		 * O​o​p​s​!​ ​S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​.
		 */
		Error: string
		/**
		 * L​o​a​d​i​n​g​.​.​.
		 */
		Loading: string
	}
	Toasts: {
		Titles: {
			/**
			 * V​o​i​c​e​ ​C​o​n​n​e​c​t​i​o​n​ ​C​l​o​s​e​d
			 */
			VoiceConnectionClosed: string
			/**
			 * V​o​i​c​e​ ​C​o​n​n​e​c​t​i​o​n​ ​E​r​r​o​r
			 */
			VoiceConnectionError: string
			/**
			 * U​n​a​b​l​e​ ​t​o​ ​a​c​c​e​s​s​ ​m​i​c​r​o​p​h​o​n​e
			 */
			UnableToAccessMicrophone: string
			/**
			 * I​n​v​i​t​e​ ​l​i​n​k​ ​c​o​p​i​e​d​ ​t​o​ ​c​l​i​p​b​o​a​r​d
			 */
			InviteLinkCopied: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​o​p​y​ ​i​n​v​i​t​e​ ​l​i​n​k
			 */
			InviteLinkCopyFailed: string
			/**
			 * U​p​l​o​a​d​ ​F​a​i​l​e​d
			 */
			UploadFailed: string
		}
		Descriptions: {
			/**
			 * V​o​i​c​e​ ​c​o​n​n​e​c​t​i​o​n​ ​f​a​i​l​e​d​ ​t​o​ ​i​n​i​t​i​a​l​i​z​e
			 */
			VoiceConnectionError: string
			/**
			 * A​t​t​a​c​h​m​e​n​t​ ​{​f​i​l​e​N​a​m​e​}​ ​f​a​i​l​e​d​ ​t​o​ ​u​p​l​o​a​d
			 * @param {string} fileName
			 */
			UploadFailed: RequiredParams<'fileName'>
		}
	}
	Time: {
		/**
		 * j​u​s​t​ ​n​o​w
		 */
		JustNow: string
		/**
		 * m​i​n​u​t​e
		 */
		Minute: string
		/**
		 * m​i​n​u​t​e​s
		 */
		Minutes: string
		/**
		 * h​o​u​r
		 */
		Hour: string
		/**
		 * h​o​u​r​s
		 */
		Hours: string
		/**
		 * d​a​y
		 */
		Day: string
		/**
		 * d​a​y​s
		 */
		Days: string
		/**
		 * w​e​e​k​s
		 */
		Weeks: string
		/**
		 * w​e​e​k
		 */
		Week: string
		/**
		 * m​o​n​t​h
		 */
		Month: string
		/**
		 * m​o​n​t​h​s
		 */
		Months: string
		/**
		 * y​e​a​r
		 */
		Year: string
		/**
		 * y​e​a​r​s
		 */
		Years: string
		/**
		 * A​g​o
		 */
		Ago: string
		/**
		 * I​n
		 */
		In: string
	}
}

export type TranslationFunctions = {
	Errors: {
		/**
		 * Error during login: {error}
		 */
		Login: (arg: { error: string }) => LocalizedString
	}
	Actions: {
		/**
		 * Sign In with {provider}
		 */
		SignInWith: (arg: { provider: string }) => LocalizedString
		/**
		 * Cancel
		 */
		Cancel: () => LocalizedString
		/**
		 * Delete
		 */
		Delete: () => LocalizedString
		/**
		 * Disconnect
		 */
		Disconnect: () => LocalizedString
		/**
		 * Go Back
		 */
		GoBack: () => LocalizedString
		/**
		 * Back
		 */
		Back: () => LocalizedString
		/**
		 * Attach File
		 */
		AttachFile: () => LocalizedString
		/**
		 * Open Emoji Selector
		 */
		OpenEmojiSelector: () => LocalizedString
		/**
		 * Sync
		 */
		Sync: () => LocalizedString
		/**
		 * Delete Channel
		 */
		DeleteChannel: () => LocalizedString
		/**
		 * Delete Category
		 */
		DeleteCategory: () => LocalizedString
		/**
		 * Create Channel
		 */
		CreateChannel: () => LocalizedString
		/**
		 * Create Category
		 */
		CreateCategory: () => LocalizedString
		/**
		 * Create Invite
		 */
		CreateInvite: () => LocalizedString
		/**
		 * Mute
		 */
		Mute: () => LocalizedString
		/**
		 * Unmute
		 */
		Unmute: () => LocalizedString
		/**
		 * Leave Server
		 */
		LeaveServer: () => LocalizedString
		/**
		 * Ban
		 */
		Ban: () => LocalizedString
		/**
		 * Join
		 */
		Join: () => LocalizedString
		/**
		 * Create
		 */
		Create: () => LocalizedString
		/**
		 * Next
		 */
		Next: () => LocalizedString
		/**
		 * Send Invite
		 */
		SendInvite: () => LocalizedString
		/**
		 * Copy Invite
		 */
		CopyInvite: () => LocalizedString
		/**
		 * Change Banner
		 */
		ChangeBanner: () => LocalizedString
		/**
		 * Unban
		 */
		Unban: () => LocalizedString
		/**
		 * Delete Invite
		 */
		DeleteInvite: () => LocalizedString
		/**
		 * Ban {displayName}
		 */
		BanMember: (arg: { displayName: string }) => LocalizedString
		/**
		 * Kick {displayName}
		 */
		KickMember: (arg: { displayName: string }) => LocalizedString
		/**
		 * Add Member
		 */
		AddMember: () => LocalizedString
		/**
		 * Assign
		 */
		Assign: () => LocalizedString
		/**
		 * Create Role
		 */
		CreateRole: () => LocalizedString
		/**
		 * Delete Server
		 */
		DeleteServer: () => LocalizedString
		/**
		 * Send Request
		 */
		SendRequest: () => LocalizedString
		/**
		 * Delete Account
		 */
		DeleteAccount: () => LocalizedString
		/**
		 * Log Out
		 */
		LogOut: () => LocalizedString
		/**
		 * Reset
		 */
		Reset: () => LocalizedString
		/**
		 * Save
		 */
		Save: () => LocalizedString
		/**
		 * Reload
		 */
		Reload: () => LocalizedString
	}
	Tooltips: {
		/**
		 * Navigate to: {guildName}
		 */
		NavigateToGuild: (arg: { guildName: string }) => LocalizedString
		/**
		 * User Dashboard
		 */
		UserDashboard: () => LocalizedString
		/**
		 * Create Server
		 */
		CreateServer: () => LocalizedString
		/**
		 * Public Servers
		 */
		PublicServers: () => LocalizedString
		/**
		 * User Settings
		 */
		UserSettings: () => LocalizedString
		/**
		 * Pinned Messages
		 */
		PinnedMessages: () => LocalizedString
		/**
		 * Ban Actions
		 */
		BanActions: () => LocalizedString
		/**
		 * Invite Actions
		 */
		InviteActions: () => LocalizedString
		/**
		 * Member Actions
		 */
		MemberActions: () => LocalizedString
		/**
		 * Create New Role
		 */
		CreateRole: () => LocalizedString
		/**
		 * 'Back to Overview'
		 */
		BackToOverview: () => LocalizedString
		/**
		 * Edit Role
		 */
		EditRole: () => LocalizedString
		/**
		 * Delete Role
		 */
		DeleteRole: () => LocalizedString
		/**
		 * Unassign From Role
		 */
		UnassignFromRole: () => LocalizedString
		/**
		 * Message {displayName}
		 */
		MessageUser: (arg: { displayName: string }) => LocalizedString
		/**
		 * Message {displayName}
		 */
		UnfriendUser: (arg: { displayName: string }) => LocalizedString
		/**
		 * Message {displayName}
		 */
		UnblockUser: (arg: { displayName: string }) => LocalizedString
		/**
		 * Accept {displayName}'s request
		 */
		AcceptUserRequest: (arg: { displayName: string }) => LocalizedString
		/**
		 * Decline {displayName}'s request
		 */
		DeclineUserRequest: (arg: { displayName: string }) => LocalizedString
		/**
		 * Cancel request to {displayName}
		 */
		CancelUserRequest: (arg: { displayName: string }) => LocalizedString
		/**
		 * Delete Session
		 */
		DeleteSession: () => LocalizedString
		/**
		 * All Roles
		 */
		AllRoles: () => LocalizedString
	}
	Selects: {
		Placeholders: {
			/**
			 * Select a category
			 */
			SelectCategory: () => LocalizedString
		}
	}
	Hints: {
		/**
		 * Are you sure you want to {type} this {subject}, this action cannot be undone?
		 */
		DeletetionWarning: (arg: { subject: string, type: string }) => LocalizedString
		/**
		 * Permissions for this channel are synced with the parent category.
		 */
		PermissionsSynced: () => LocalizedString
		/**
		 * Permissions are not synced with Category
		 */
		PermissionsUnsynced: () => LocalizedString
		/**
		 * Users with 'Manage Messages' can pin messages
		 */
		PinMessages: () => LocalizedString
		/**
		 * This channel doesn't have any pinned messages... yet!
		 */
		NoPinnedMessages: () => LocalizedString
		/**
		 * Are you sure you want to ban {displayName}, they won't be able to return unless
	        unbanned.
		 */
		BanUser: (arg: { displayName: string }) => LocalizedString
		/**
		 * Sending...
		 */
		InviteSending: () => LocalizedString
		/**
		 * Invite Sent
		 */
		InviteSent: () => LocalizedString
		/**
		 * Invite Failed
		 */
		InviteFailed: () => LocalizedString
		/**
		 * Applies to all members of this server
		 */
		DefaultRole: () => LocalizedString
		/**
		 * Your display name is visible to everyone.
		 */
		DisplayName: () => LocalizedString
		/**
		 * Deleting your account cannot be undone.
		 */
		AccountDeletion: () => LocalizedString
		/**
		 * Careful - You have unsaved changes!
		 */
		UnsavedChanges: () => LocalizedString
		/**
		 * Accord encountered an error, see the console for technical details.
		 */
		Error: () => LocalizedString
	}
	Permissions: {
		Titles: {
			/**
			 * View Channel
			 */
			ViewChannel: () => LocalizedString
			/**
			 * Manage Channels
			 */
			ManageChannels: () => LocalizedString
			/**
			 * Send Messages
			 */
			SendMessages: () => LocalizedString
			/**
			 * Manage Messages
			 */
			ManageMessages: () => LocalizedString
			/**
			 * Manage Guild
			 */
			ManageGuild: () => LocalizedString
			/**
			 * Guild Admin
			 */
			GuildAdmin: () => LocalizedString
		}
		Descriptions: {
			/**
			 * Allows users to view channels.
			 */
			ViewChannel: () => LocalizedString
			/**
			 * Allows members to create, modify or delete channels.
			 */
			ManageChannels: () => LocalizedString
			/**
			 * Allows users to send messages within channels
			 */
			SendMessages: () => LocalizedString
			/**
			 * Allows users to manage messages (including other members messages) in channels
			 */
			ManageMessages: () => LocalizedString
			/**
			 * Allows users to manager the server, create channels, roles etc.
			 */
			ManageGuild: () => LocalizedString
			/**
			 * In addition to all other permissions, users may ban/unban users.
			 */
			GuildAdmin: () => LocalizedString
		}
	}
	Toggles: {
		Labels: {
			/**
			 * Allow friend requests
			 */
			AllowFriendRequests: () => LocalizedString
			/**
			 * Allow server member DMs
			 */
			AllowServerMemberDMs: () => LocalizedString
			/**
			 * Discoverable
			 */
			Discoverable: () => LocalizedString
			/**
			 * Private Channel
			 */
			PrivateChannel: () => LocalizedString
			/**
			 * Private Category
			 */
			PrivateCategory: () => LocalizedString
		}
		HelperText: {
			/**
			 * Allow users to send friend requests
			 */
			AllowFriendRequests: () => LocalizedString
			/**
			 * Allow members of servers you have joined send you messages
			 */
			AllowServerMemberDMs: () => LocalizedString
			/**
			 * Set server visibility in server browser
			 */
			Discoverable: () => LocalizedString
			/**
			 * Restrict channel to specific roles
			 */
			RestrictChannel: () => LocalizedString
			/**
			 * Restrict category to specific roles
			 */
			RestrictCategory: () => LocalizedString
		}
	}
	Inputs: {
		Placeholders: {
			/**
			 * Filter Requests
			 */
			FilterRequests: () => LocalizedString
			/**
			 * Filter Friends
			 */
			FilterFriends: () => LocalizedString
			/**
			 * Filter Bans
			 */
			FilterBans: () => LocalizedString
			/**
			 * Filter Roles
			 */
			FilterRoles: () => LocalizedString
			/**
			 * Filter Members
			 */
			FilterMembers: () => LocalizedString
			/**
			 * Filter Blocks
			 */
			FilterBlocks: () => LocalizedString
			/**
			 * Filter Servers
			 */
			FilterServers: () => LocalizedString
			/**
			 * Enter a name
			 */
			EnterName: () => LocalizedString
			/**
			 * Enter a username
			 */
			EnterUsername: () => LocalizedString
			/**
			 * Enter a topic
			 */
			EnterTopic: () => LocalizedString
			/**
			 * Reason for ban
			 */
			BanReason: () => LocalizedString
			/**
			 * Search for servers...
			 */
			SearchServers: () => LocalizedString
			/**
			 * Search for friends...
			 */
			SearchFriends: () => LocalizedString
			/**
			 * Channel name
			 */
			ChannelName: () => LocalizedString
			/**
			 * Channel topic
			 */
			ChannelTopic: () => LocalizedString
			/**
			 * Category name
			 */
			CategoryName: () => LocalizedString
			/**
			 * Give your server a name
			 */
			ServerName: () => LocalizedString
			/**
			 * What's your server about?
			 */
			ServerDescription: () => LocalizedString
			/**
			 * Write a message...
			 */
			GrantedWriteMessage: () => LocalizedString
			/**
			 * You are not permitted to post in this channel
			 */
			DeniedWriteMessage: () => LocalizedString
		}
		Labels: {
			/**
			 * Enter the {subject} name below to confirm.
			 */
			DeletionConfirmation: (arg: { subject: string }) => LocalizedString
			/**
			 * Display Name
			 */
			DisplayName: () => LocalizedString
			/**
			 * Username
			 */
			Username: () => LocalizedString
			/**
			 * Server Description
			 */
			ServerDescription: () => LocalizedString
			/**
			 * Server Name
			 */
			ServerName: () => LocalizedString
			/**
			 * Channel Name
			 */
			ChannelName: () => LocalizedString
			/**
			 * Category Name
			 */
			CategoryName: () => LocalizedString
			/**
			 * Channel Topic
			 */
			ChannelTopic: () => LocalizedString
		}
	}
	RadioGroups: {
		Names: {
			/**
			 * Text
			 */
			Text: () => LocalizedString
			/**
			 * Voice
			 */
			Voice: () => LocalizedString
		}
		Descriptions: {
			/**
			 * Send messages, images, emoji etc.
			 */
			Text: () => LocalizedString
			/**
			 * Voice chat with friends.
			 */
			Voice: () => LocalizedString
		}
	}
	Tables: {
		Heads: {
			/**
			 * Id
			 */
			ID: () => LocalizedString
			/**
			 * Expires
			 */
			Expires: () => LocalizedString
			/**
			 * Current Session
			 */
			CurrentSession: () => LocalizedString
			/**
			 * User
			 */
			User: () => LocalizedString
			/**
			 * Banned
			 */
			Banned: () => LocalizedString
			/**
			 * Reason
			 */
			Reason: () => LocalizedString
			/**
			 * Actions
			 */
			Actions: () => LocalizedString
			/**
			 * Creator
			 */
			Creator: () => LocalizedString
			/**
			 * Created
			 */
			Created: () => LocalizedString
			/**
			 * Uses
			 */
			Uses: () => LocalizedString
			/**
			 * Name
			 */
			Name: () => LocalizedString
			/**
			 * Member Since
			 */
			MemberSince: () => LocalizedString
			/**
			 * Joined Accord
			 */
			JoinedAccord: () => LocalizedString
			/**
			 * Is Creator
			 */
			IsCreator: () => LocalizedString
			/**
			 * Roles
			 */
			Roles: () => LocalizedString
		}
	}
	General: {
		/**
		 * Outgoing Request
		 */
		OutgoingRequest: () => LocalizedString
		/**
		 * Incoming Request
		 */
		IncomingRequest: () => LocalizedString
		/**
		 * Custom Roles
		 */
		CustomRoles: () => LocalizedString
		/**
		 * Default Permissions
		 */
		DefaultPermissions: () => LocalizedString
		/**
		 * Roles
		 */
		Roles: () => LocalizedString
		/**
		 * Edit Role - {roleName}
		 */
		EditRole: (arg: { roleName: string }) => LocalizedString
		/**
		 * Members
		 */
		Members: () => LocalizedString
		/**
		 * Server Members
		 */
		ServerMembers: () => LocalizedString
		/**
		 * Invites
		 */
		Invites: () => LocalizedString
		/**
		 * Server Bans
		 */
		ServerBans: () => LocalizedString
		/**
		 * Server Banner
		 */
		ServerBanner: () => LocalizedString
		/**
		 * Display
		 */
		Display: () => LocalizedString
		/**
		 * Server Category
		 */
		ServerCategory: () => LocalizedString
		/**
		 * Create Server
		 */
		CreateServer: () => LocalizedString
		/**
		 * Channel Type
		 */
		ChannelType: () => LocalizedString
		/**
		 * Home
		 */
		Home: () => LocalizedString
		/**
		 * Discover
		 */
		Discover: () => LocalizedString
		/**
		 * Discovery
		 */
		Discovery: () => LocalizedString
		/**
		 * Query: {query}
		 */
		Query: (arg: { query: string }) => LocalizedString
		/**
		 * {count} Members(s)
		 */
		GuildMemberCount: (arg: { count: number }) => LocalizedString
		/**
		 * {count} Friends
		 */
		FriendCount: (arg: { count: number }) => LocalizedString
		/**
		 * Server Roles
		 */
		ServerRoles: () => LocalizedString
		/**
		 * Assigned Roles - {count}
		 */
		AssignedRoles: (arg: { count: number }) => LocalizedString
		/**
		 * Overview
		 */
		Overview: () => LocalizedString
		/**
		 * Permissions
		 */
		Permissions: () => LocalizedString
		/**
		 * Danger Zone
		 */
		DangerZone: () => LocalizedString
		/**
		 * Voice Connected
		 */
		VoiceConnected: () => LocalizedString
		/**
		 * Not Found!
		 */
		NotFound: () => LocalizedString
		/**
		 * Pinned Messages
		 */
		PinnedMessages: () => LocalizedString
		/**
		 * Channel Settings
		 */
		ChannelSettings: () => LocalizedString
		/**
		 * Category Settings
		 */
		CategorySettings: () => LocalizedString
		/**
		 * Server Settings
		 */
		ServerSettings: () => LocalizedString
		/**
		 * Ban User
		 */
		BanUser: () => LocalizedString
		/**
		 * Find your community on Accord
		 */
		FindCommunity: () => LocalizedString
		/**
		 * From gaming, to music, to learning, there's a place for you.
		 */
		Community: () => LocalizedString
		/**
		 * Popular Communities
		 */
		PopularCommunities: () => LocalizedString
		/**
		 * Joined
		 */
		Joined: () => LocalizedString
		/**
		 * Send invite to friends
		 */
		SendInviteToFriends: () => LocalizedString
		/**
		 * Or copy an invite link to paste elsewhere
		 */
		CopyInviteLink: () => LocalizedString
		/**
		 * This image will display at the top of your channels list.
		 */
		ImageDisplay: () => LocalizedString
		/**
		 * Assign Members
		 */
		AssignMembers: () => LocalizedString
		/**
		 * Role Name
		 */
		RoleName: () => LocalizedString
		/**
		 * User Management
		 */
		UserManagement: () => LocalizedString
		/**
		 * Add Friend
		 */
		AddFriend: () => LocalizedString
		/**
		 * Friends
		 */
		Friends: () => LocalizedString
		/**
		 * Requests
		 */
		Requests: () => LocalizedString
		/**
		 * Blocked
		 */
		Blocked: () => LocalizedString
		/**
		 * Direct Messages
		 */
		DirectMessages: () => LocalizedString
		/**
		 * Group Channel
		 */
		GroupChannel: () => LocalizedString
		/**
		 * Servers Manager
		 */
		ServersManager: () => LocalizedString
		/**
		 * Yes
		 */
		Yes: () => LocalizedString
		/**
		 * No
		 */
		No: () => LocalizedString
		/**
		 * My Account
		 */
		MyAccount: () => LocalizedString
		/**
		 * Friend Requests
		 */
		FriendRequests: () => LocalizedString
		/**
		 * Account Deletion
		 */
		AccountDeletion: () => LocalizedString
		/**
		 * Server Privacy
		 */
		ServerPrivacy: () => LocalizedString
		/**
		 * Sessions Manager
		 */
		SessionsManager: () => LocalizedString
		/**
		 * User Settings
		 */
		UserSettings: () => LocalizedString
		/**
		 * Servers
		 */
		Servers: () => LocalizedString
		/**
		 * Sessions
		 */
		Sessions: () => LocalizedString
		/**
		 * Roles - {count}
		 */
		RolesCount: (arg: { count: number }) => LocalizedString
		/**
		 * Member Since
		 */
		MemberSince: () => LocalizedString
		/**
		 * Accord Member Since
		 */
		AccordMemberSince: () => LocalizedString
		/**
		 * Oops! Something went wrong.
		 */
		Error: () => LocalizedString
		/**
		 * Loading...
		 */
		Loading: () => LocalizedString
	}
	Toasts: {
		Titles: {
			/**
			 * Voice Connection Closed
			 */
			VoiceConnectionClosed: () => LocalizedString
			/**
			 * Voice Connection Error
			 */
			VoiceConnectionError: () => LocalizedString
			/**
			 * Unable to access microphone
			 */
			UnableToAccessMicrophone: () => LocalizedString
			/**
			 * Invite link copied to clipboard
			 */
			InviteLinkCopied: () => LocalizedString
			/**
			 * Failed to copy invite link
			 */
			InviteLinkCopyFailed: () => LocalizedString
			/**
			 * Upload Failed
			 */
			UploadFailed: () => LocalizedString
		}
		Descriptions: {
			/**
			 * Voice connection failed to initialize
			 */
			VoiceConnectionError: () => LocalizedString
			/**
			 * Attachment {fileName} failed to upload
			 */
			UploadFailed: (arg: { fileName: string }) => LocalizedString
		}
	}
	Time: {
		/**
		 * just now
		 */
		JustNow: () => LocalizedString
		/**
		 * minute
		 */
		Minute: () => LocalizedString
		/**
		 * minutes
		 */
		Minutes: () => LocalizedString
		/**
		 * hour
		 */
		Hour: () => LocalizedString
		/**
		 * hours
		 */
		Hours: () => LocalizedString
		/**
		 * day
		 */
		Day: () => LocalizedString
		/**
		 * days
		 */
		Days: () => LocalizedString
		/**
		 * weeks
		 */
		Weeks: () => LocalizedString
		/**
		 * week
		 */
		Week: () => LocalizedString
		/**
		 * month
		 */
		Month: () => LocalizedString
		/**
		 * months
		 */
		Months: () => LocalizedString
		/**
		 * year
		 */
		Year: () => LocalizedString
		/**
		 * years
		 */
		Years: () => LocalizedString
		/**
		 * Ago
		 */
		Ago: () => LocalizedString
		/**
		 * In
		 */
		In: () => LocalizedString
	}
}

export type Formatters = {}
