env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - prettier
rules:
  react-hooks/exhaustive-deps: "warn"
  react/react-in-jsx-scope: off
  camelcase: error
  spaced-comment: error
  no-duplicate-imports: off
  react/prop-types: off
settings:
  import/resolver:
    - typescript: true
  react:
    version: 'detect'